//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ACNMFA" minOccurs="0"/>
 *         &lt;element ref="{}ACNM1A" minOccurs="0"/>
 *         &lt;element ref="{}ACNM2A" minOccurs="0"/>
 *         &lt;element ref="{}ACNM3A" minOccurs="0"/>
 *         &lt;element ref="{}ACNM7A" minOccurs="0"/>
 *         &lt;element ref="{}ACNMFE" minOccurs="0"/>
 *         &lt;element ref="{}ACNM1E" minOccurs="0"/>
 *         &lt;element ref="{}ACNM2E" minOccurs="0"/>
 *         &lt;element ref="{}ACNM3E" minOccurs="0"/>
 *         &lt;element ref="{}ACNM7E" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acnmfa",
    "acnm1A",
    "acnm2A",
    "acnm3A",
    "acnm7A",
    "acnmfe",
    "acnm1E",
    "acnm2E",
    "acnm3E",
    "acnm7E"
})
@XmlRootElement(name = "ACNAM")
public class ACNAM {

    @XmlElement(name = "ACNMFA")
    protected ACNMFA acnmfa;
    @XmlElement(name = "ACNM1A")
    protected ACNM1A acnm1A;
    @XmlElement(name = "ACNM2A")
    protected ACNM2A acnm2A;
    @XmlElement(name = "ACNM3A")
    protected ACNM3A acnm3A;
    @XmlElement(name = "ACNM7A")
    protected ACNM7A acnm7A;
    @XmlElement(name = "ACNMFE")
    protected String acnmfe;
    @XmlElement(name = "ACNM1E")
    protected String acnm1E;
    @XmlElement(name = "ACNM2E")
    protected String acnm2E;
    @XmlElement(name = "ACNM3E")
    protected String acnm3E;
    @XmlElement(name = "ACNM7E")
    protected String acnm7E;

    /**
     * Gets the value of the acnmfa property.
     * 
     * @return
     *     possible object is
     *     {@link ACNMFA }
     *     
     */
    public ACNMFA getACNMFA() {
        return acnmfa;
    }

    /**
     * Sets the value of the acnmfa property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNMFA }
     *     
     */
    public void setACNMFA(ACNMFA value) {
        this.acnmfa = value;
    }

    /**
     * Gets the value of the acnm1A property.
     * 
     * @return
     *     possible object is
     *     {@link ACNM1A }
     *     
     */
    public ACNM1A getACNM1A() {
        return acnm1A;
    }

    /**
     * Sets the value of the acnm1A property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNM1A }
     *     
     */
    public void setACNM1A(ACNM1A value) {
        this.acnm1A = value;
    }

    /**
     * Gets the value of the acnm2A property.
     * 
     * @return
     *     possible object is
     *     {@link ACNM2A }
     *     
     */
    public ACNM2A getACNM2A() {
        return acnm2A;
    }

    /**
     * Sets the value of the acnm2A property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNM2A }
     *     
     */
    public void setACNM2A(ACNM2A value) {
        this.acnm2A = value;
    }

    /**
     * Gets the value of the acnm3A property.
     * 
     * @return
     *     possible object is
     *     {@link ACNM3A }
     *     
     */
    public ACNM3A getACNM3A() {
        return acnm3A;
    }

    /**
     * Sets the value of the acnm3A property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNM3A }
     *     
     */
    public void setACNM3A(ACNM3A value) {
        this.acnm3A = value;
    }

    /**
     * Gets the value of the acnm7A property.
     * 
     * @return
     *     possible object is
     *     {@link ACNM7A }
     *     
     */
    public ACNM7A getACNM7A() {
        return acnm7A;
    }

    /**
     * Sets the value of the acnm7A property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNM7A }
     *     
     */
    public void setACNM7A(ACNM7A value) {
        this.acnm7A = value;
    }

    /**
     * Gets the value of the acnmfe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNMFE() {
        return acnmfe;
    }

    /**
     * Sets the value of the acnmfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNMFE(String value) {
        this.acnmfe = value;
    }

    /**
     * Gets the value of the acnm1E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNM1E() {
        return acnm1E;
    }

    /**
     * Sets the value of the acnm1E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNM1E(String value) {
        this.acnm1E = value;
    }

    /**
     * Gets the value of the acnm2E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNM2E() {
        return acnm2E;
    }

    /**
     * Sets the value of the acnm2E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNM2E(String value) {
        this.acnm2E = value;
    }

    /**
     * Gets the value of the acnm3E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNM3E() {
        return acnm3E;
    }

    /**
     * Sets the value of the acnm3E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNM3E(String value) {
        this.acnm3E = value;
    }

    /**
     * Gets the value of the acnm7E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNM7E() {
        return acnm7E;
    }

    /**
     * Sets the value of the acnm7E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNM7E(String value) {
        this.acnm7E = value;
    }

}
