package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CA_LOAD_DT" minOccurs="0"/>
 *         &lt;element ref="{}CA_CADT" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD1A" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD2A" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD1E" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD2E" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD6" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD7" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD8A" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD8E" minOccurs="0"/>
 *         &lt;element ref="{}CA_CAD9" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "caloaddt",
    "cacadt",
    "cacad1A",
    "cacad2A",
    "cacad1E",
    "cacad2E",
    "cacad6",
    "cacad7",
    "cacad8A",
    "cacad8E",
    "cacad9"
})
@XmlRootElement(name = "ADDRESS")
public class ADDRESS {

    @XmlElement(name = "CA_LOAD_DT")
    protected String caloaddt;
    @XmlElement(name = "CA_CADT")
    protected String cacadt;
    @XmlElement(name = "CA_CAD1A")
    protected CACAD1A cacad1A;
    @XmlElement(name = "CA_CAD2A")
    protected CACAD2A cacad2A;
    @XmlElement(name = "CA_CAD1E")
    protected String cacad1E;
    @XmlElement(name = "CA_CAD2E")
    protected String cacad2E;
    @XmlElement(name = "CA_CAD6")
    protected String cacad6;
    @XmlElement(name = "CA_CAD7")
    protected String cacad7;
    @XmlElement(name = "CA_CAD8A")
    protected CACAD8A cacad8A;
    @XmlElement(name = "CA_CAD8E")
    protected String cacad8E;
    @XmlElement(name = "CA_CAD9")
    protected String cacad9;

    /**
     * Gets the value of the caloaddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALOADDT() {
        return caloaddt;
    }

    /**
     * Sets the value of the caloaddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALOADDT(String value) {
        this.caloaddt = value;
    }

    /**
     * Gets the value of the cacadt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACADT() {
        return cacadt;
    }

    /**
     * Sets the value of the cacadt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACADT(String value) {
        this.cacadt = value;
    }

    /**
     * Gets the value of the cacad1A property.
     * 
     * @return
     *     possible object is
     *     {@link CACAD1A }
     *     
     */
    public CACAD1A getCACAD1A() {
        return cacad1A;
    }

    /**
     * Sets the value of the cacad1A property.
     * 
     * @param value
     *     allowed object is
     *     {@link CACAD1A }
     *     
     */
    public void setCACAD1A(CACAD1A value) {
        this.cacad1A = value;
    }

    /**
     * Gets the value of the cacad2A property.
     * 
     * @return
     *     possible object is
     *     {@link CACAD2A }
     *     
     */
    public CACAD2A getCACAD2A() {
        return cacad2A;
    }

    /**
     * Sets the value of the cacad2A property.
     * 
     * @param value
     *     allowed object is
     *     {@link CACAD2A }
     *     
     */
    public void setCACAD2A(CACAD2A value) {
        this.cacad2A = value;
    }

    /**
     * Gets the value of the cacad1E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD1E() {
        return cacad1E;
    }

    /**
     * Sets the value of the cacad1E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD1E(String value) {
        this.cacad1E = value;
    }

    /**
     * Gets the value of the cacad2E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD2E() {
        return cacad2E;
    }

    /**
     * Sets the value of the cacad2E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD2E(String value) {
        this.cacad2E = value;
    }

    /**
     * Gets the value of the cacad6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD6() {
        return cacad6;
    }

    /**
     * Sets the value of the cacad6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD6(String value) {
        this.cacad6 = value;
    }

    /**
     * Gets the value of the cacad7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD7() {
        return cacad7;
    }

    /**
     * Sets the value of the cacad7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD7(String value) {
        this.cacad7 = value;
    }

    /**
     * Gets the value of the cacad8A property.
     * 
     * @return
     *     possible object is
     *     {@link CACAD8A }
     *     
     */
    public CACAD8A getCACAD8A() {
        return cacad8A;
    }

    /**
     * Sets the value of the cacad8A property.
     * 
     * @param value
     *     allowed object is
     *     {@link CACAD8A }
     *     
     */
    public void setCACAD8A(CACAD8A value) {
        this.cacad8A = value;
    }

    /**
     * Gets the value of the cacad8E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD8E() {
        return cacad8E;
    }

    /**
     * Sets the value of the cacad8E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD8E(String value) {
        this.cacad8E = value;
    }

    /**
     * Gets the value of the cacad9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCACAD9() {
        return cacad9;
    }

    /**
     * Sets the value of the cacad9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCACAD9(String value) {
        this.cacad9 = value;
    }

}
