package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ACNAM"/>
 *         &lt;element ref="{}ACDOB"/>
 *         &lt;element ref="{}ACGND"/>
 *         &lt;element ref="{}ACMAR"/>
 *         &lt;element ref="{}ACNAT"/>
 *         &lt;element ref="{}ACEML"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acnam",
    "acdob",
    "acgnd",
    "acmar",
    "acnat",
    "aceml"
})
@XmlRootElement(name = "AVAILABLE")
public class AVAILABLE {

    @XmlElement(name = "ACNAM", required = true)
    protected ACNAM acnam;
    @XmlElement(name = "ACDOB", required = true)
    protected String acdob;
    @XmlElement(name = "ACGND", required = true)
    protected String acgnd;
    @XmlElement(name = "ACMAR", required = true)
    protected String acmar;
    @XmlElement(name = "ACNAT", required = true)
    protected String acnat;
    @XmlElement(name = "ACEML", required = true)
    protected String aceml;

    /**
     * Gets the value of the acnam property.
     * 
     * @return
     *     possible object is
     *     {@link ACNAM }
     *     
     */
    public ACNAM getACNAM() {
        return acnam;
    }

    /**
     * Sets the value of the acnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link ACNAM }
     *     
     */
    public void setACNAM(ACNAM value) {
        this.acnam = value;
    }

    /**
     * Gets the value of the acdob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACDOB() {
        return acdob;
    }

    /**
     * Sets the value of the acdob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACDOB(String value) {
        this.acdob = value;
    }

    /**
     * Gets the value of the acgnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACGND() {
        return acgnd;
    }

    /**
     * Sets the value of the acgnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACGND(String value) {
        this.acgnd = value;
    }

    /**
     * Gets the value of the acmar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACMAR() {
        return acmar;
    }

    /**
     * Sets the value of the acmar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACMAR(String value) {
        this.acmar = value;
    }

    /**
     * Gets the value of the acnat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACNAT() {
        return acnat;
    }

    /**
     * Sets the value of the acnat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACNAT(String value) {
        this.acnat = value;
    }

    /**
     * Gets the value of the aceml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACEML() {
        return aceml;
    }

    /**
     * Sets the value of the aceml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACEML(String value) {
        this.aceml = value;
    }

}
