package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BC_PRD"/>
 *         &lt;element ref="{}BC_CRDTR"/>
 *         &lt;element ref="{}BC_CHECK_NO"/>
 *         &lt;element ref="{}BC_LOAD_DT"/>
 *         &lt;element ref="{}BC_ORIG_AMT"/>
 *         &lt;element ref="{}BC_CUB"/>
 *         &lt;element ref="{}BC_STAT"/>
 *         &lt;element ref="{}BC_SETTLD_DATE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bcprd",
    "bccrdtr",
    "bccheckno",
    "bcloaddt",
    "bcorigamt",
    "bccub",
    "bcstat",
    "bcsettlddate"
})
@XmlRootElement(name = "BOUNCED_CHECK")
public class BOUNCEDCHECK {

    @XmlElement(name = "BC_PRD", required = true)
    protected String bcprd;
    @XmlElement(name = "BC_CRDTR", required = true)
    protected String bccrdtr;
    @XmlElement(name = "BC_CHECK_NO", required = true)
    protected String bccheckno;
    @XmlElement(name = "BC_LOAD_DT", required = true)
    protected String bcloaddt;
    @XmlElement(name = "BC_ORIG_AMT", required = true)
    protected String bcorigamt;
    @XmlElement(name = "BC_CUB", required = true)
    protected String bccub;
    @XmlElement(name = "BC_STAT", required = true)
    protected String bcstat;
    @XmlElement(name = "BC_SETTLD_DATE", required = true)
    protected String bcsettlddate;

    /**
     * Gets the value of the bcprd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCPRD() {
        return bcprd;
    }

    /**
     * Sets the value of the bcprd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCPRD(String value) {
        this.bcprd = value;
    }

    /**
     * Gets the value of the bccrdtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCCRDTR() {
        return bccrdtr;
    }

    /**
     * Sets the value of the bccrdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCCRDTR(String value) {
        this.bccrdtr = value;
    }

    /**
     * Gets the value of the bccheckno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCCHECKNO() {
        return bccheckno;
    }

    /**
     * Sets the value of the bccheckno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCCHECKNO(String value) {
        this.bccheckno = value;
    }

    /**
     * Gets the value of the bcloaddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCLOADDT() {
        return bcloaddt;
    }

    /**
     * Sets the value of the bcloaddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCLOADDT(String value) {
        this.bcloaddt = value;
    }

    /**
     * Gets the value of the bcorigamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCORIGAMT() {
        return bcorigamt;
    }

    /**
     * Sets the value of the bcorigamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCORIGAMT(String value) {
        this.bcorigamt = value;
    }

    /**
     * Gets the value of the bccub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCCUB() {
        return bccub;
    }

    /**
     * Sets the value of the bccub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCCUB(String value) {
        this.bccub = value;
    }

    /**
     * Gets the value of the bcstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCSTAT() {
        return bcstat;
    }

    /**
     * Sets the value of the bcstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCSTAT(String value) {
        this.bcstat = value;
    }

    /**
     * Gets the value of the bcsettlddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBCSETTLDDATE() {
        return bcsettlddate;
    }

    /**
     * Sets the value of the bcsettlddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBCSETTLDDATE(String value) {
        this.bcsettlddate = value;
    }

}
