package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CID1"/>
 *         &lt;element ref="{}CID2"/>
 *         &lt;element ref="{}CID3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cid1",
    "cid2",
    "cid3"
})
@XmlRootElement(name = "CID")
public class CID {

    @XmlElement(name = "CID1", required = true)
    protected String cid1;
    @XmlElement(name = "CID2", required = true)
    protected String cid2;
    @XmlElement(name = "CID3", required = true)
    protected String cid3;

    /**
     * Gets the value of the cid1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCID1() {
        return cid1;
    }

    /**
     * Sets the value of the cid1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCID1(String value) {
        this.cid1 = value;
    }

    /**
     * Gets the value of the cid2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCID2() {
        return cid2;
    }

    /**
     * Sets the value of the cid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCID2(String value) {
        this.cid2 = value;
    }

    /**
     * Gets the value of the cid3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCID3() {
        return cid3;
    }

    /**
     * Sets the value of the cid3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCID3(String value) {
        this.cid3 = value;
    }

}
