package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CI_CRDTR"/>
 *         &lt;element ref="{}CI_PRD"/>
 *         &lt;element ref="{}CI_ACC_NO"/>
 *         &lt;element ref="{}CI_LIMIT"/>
 *         &lt;element ref="{}CI_ISSU_DT"/>
 *         &lt;element ref="{}CI_PROD_EXP_DT"/>
 *         &lt;element ref="{}CI_STATUS"/>
 *         &lt;element ref="{}CI_CLSD_DT"/>
 *         &lt;element ref="{}CI_TNR"/>
 *         &lt;element ref="{}CI_FRQ"/>
 *         &lt;element ref="{}CI_INSTL"/>
 *         &lt;element ref="{}CI_SAL"/>
 *         &lt;element ref="{}CI_SEC"/>
 *         &lt;element ref="{}CI_CUB"/>
 *         &lt;element ref="{}CI_ODB"/>
 *         &lt;element ref="{}CI_LAST_AMT_PD"/>
 *         &lt;element ref="{}CI_LAST_PAY_DT"/>
 *         &lt;element ref="{}CI_AS_OF_DT"/>
 *         &lt;element ref="{}CI_NXT_DU_DT"/>
 *         &lt;element ref="{}CI_SUMMRY"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cicrdtr",
    "ciprd",
    "ciaccno",
    "cilimit",
    "ciissudt",
    "ciprodexpdt",
    "cistatus",
    "ciclsddt",
    "citnr",
    "cifrq",
    "ciinstl",
    "cisal",
    "cisec",
    "cicub",
    "ciodb",
    "cilastamtpd",
    "cilastpaydt",
    "ciasofdt",
    "cinxtdudt",
    "cisummry"
})
@XmlRootElement(name = "CI_DETAIL")
public class CIDETAIL {

    @XmlElement(name = "CI_CRDTR", required = true)
    protected String cicrdtr;
    @XmlElement(name = "CI_PRD", required = true)
    protected String ciprd;
    @XmlElement(name = "CI_ACC_NO", required = true)
    protected String ciaccno;
    @XmlElement(name = "CI_LIMIT", required = true)
    protected String cilimit;
    @XmlElement(name = "CI_ISSU_DT", required = true)
    protected String ciissudt;
    @XmlElement(name = "CI_PROD_EXP_DT", required = true)
    protected String ciprodexpdt;
    @XmlElement(name = "CI_STATUS", required = true)
    protected String cistatus;
    @XmlElement(name = "CI_CLSD_DT", required = true)
    protected String ciclsddt;
    @XmlElement(name = "CI_TNR", required = true)
    protected String citnr;
    @XmlElement(name = "CI_FRQ", required = true)
    protected String cifrq;
    @XmlElement(name = "CI_INSTL", required = true)
    protected String ciinstl;
    @XmlElement(name = "CI_SAL", required = true)
    protected String cisal;
    @XmlElement(name = "CI_SEC", required = true)
    protected String cisec;
    @XmlElement(name = "CI_CUB", required = true)
    protected String cicub;
    @XmlElement(name = "CI_ODB", required = true)
    protected String ciodb;
    @XmlElement(name = "CI_LAST_AMT_PD", required = true)
    protected String cilastamtpd;
    @XmlElement(name = "CI_LAST_PAY_DT", required = true)
    protected String cilastpaydt;
    @XmlElement(name = "CI_AS_OF_DT", required = true)
    protected String ciasofdt;
    @XmlElement(name = "CI_NXT_DU_DT", required = true)
    protected String cinxtdudt;
    @XmlElement(name = "CI_SUMMRY", required = true)
    protected String cisummry;

    /**
     * Gets the value of the cicrdtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCICRDTR() {
        return cicrdtr;
    }

    /**
     * Sets the value of the cicrdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCICRDTR(String value) {
        this.cicrdtr = value;
    }

    /**
     * Gets the value of the ciprd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIPRD() {
        return ciprd;
    }

    /**
     * Sets the value of the ciprd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIPRD(String value) {
        this.ciprd = value;
    }

    /**
     * Gets the value of the ciaccno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIACCNO() {
        return ciaccno;
    }

    /**
     * Sets the value of the ciaccno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIACCNO(String value) {
        this.ciaccno = value;
    }

    /**
     * Gets the value of the cilimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCILIMIT() {
        return cilimit;
    }

    /**
     * Sets the value of the cilimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCILIMIT(String value) {
        this.cilimit = value;
    }

    /**
     * Gets the value of the ciissudt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIISSUDT() {
        return ciissudt;
    }

    /**
     * Sets the value of the ciissudt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIISSUDT(String value) {
        this.ciissudt = value;
    }

    /**
     * Gets the value of the ciprodexpdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIPRODEXPDT() {
        return ciprodexpdt;
    }

    /**
     * Sets the value of the ciprodexpdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIPRODEXPDT(String value) {
        this.ciprodexpdt = value;
    }

    /**
     * Gets the value of the cistatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCISTATUS() {
        return cistatus;
    }

    /**
     * Sets the value of the cistatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCISTATUS(String value) {
        this.cistatus = value;
    }

    /**
     * Gets the value of the ciclsddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCICLSDDT() {
        return ciclsddt;
    }

    /**
     * Sets the value of the ciclsddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCICLSDDT(String value) {
        this.ciclsddt = value;
    }

    /**
     * Gets the value of the citnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCITNR() {
        return citnr;
    }

    /**
     * Sets the value of the citnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCITNR(String value) {
        this.citnr = value;
    }

    /**
     * Gets the value of the cifrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIFRQ() {
        return cifrq;
    }

    /**
     * Sets the value of the cifrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIFRQ(String value) {
        this.cifrq = value;
    }

    /**
     * Gets the value of the ciinstl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIINSTL() {
        return ciinstl;
    }

    /**
     * Sets the value of the ciinstl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIINSTL(String value) {
        this.ciinstl = value;
    }

    /**
     * Gets the value of the cisal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCISAL() {
        return cisal;
    }

    /**
     * Sets the value of the cisal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCISAL(String value) {
        this.cisal = value;
    }

    /**
     * Gets the value of the cisec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCISEC() {
        return cisec;
    }

    /**
     * Sets the value of the cisec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCISEC(String value) {
        this.cisec = value;
    }

    /**
     * Gets the value of the cicub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCICUB() {
        return cicub;
    }

    /**
     * Sets the value of the cicub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCICUB(String value) {
        this.cicub = value;
    }

    /**
     * Gets the value of the ciodb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIODB() {
        return ciodb;
    }

    /**
     * Sets the value of the ciodb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIODB(String value) {
        this.ciodb = value;
    }

    /**
     * Gets the value of the cilastamtpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCILASTAMTPD() {
        return cilastamtpd;
    }

    /**
     * Sets the value of the cilastamtpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCILASTAMTPD(String value) {
        this.cilastamtpd = value;
    }

    /**
     * Gets the value of the cilastpaydt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCILASTPAYDT() {
        return cilastpaydt;
    }

    /**
     * Sets the value of the cilastpaydt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCILASTPAYDT(String value) {
        this.cilastpaydt = value;
    }

    /**
     * Gets the value of the ciasofdt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCIASOFDT() {
        return ciasofdt;
    }

    /**
     * Sets the value of the ciasofdt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCIASOFDT(String value) {
        this.ciasofdt = value;
    }

    /**
     * Gets the value of the cinxtdudt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCINXTDUDT() {
        return cinxtdudt;
    }

    /**
     * Sets the value of the cinxtdudt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCINXTDUDT(String value) {
        this.cinxtdudt = value;
    }

    /**
     * Gets the value of the cisummry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCISUMMRY() {
        return cisummry;
    }

    /**
     * Sets the value of the cisummry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCISUMMRY(String value) {
        this.cisummry = value;
    }

}
