package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DF_PRD"/>
 *         &lt;element ref="{}DF_CAPL" minOccurs="0"/>
 *         &lt;element ref="{}DF_ACC_NO"/>
 *         &lt;element ref="{}DF_CRDTR"/>
 *         &lt;element ref="{}DF_LOAD_DT"/>
 *         &lt;element ref="{}DF_ORIG_AMT"/>
 *         &lt;element ref="{}DF_CUB"/>
 *         &lt;element ref="{}DF_STAT"/>
 *         &lt;element ref="{}DF_SETTLD_DATE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dfprd",
    "dfcapl",
    "dfaccno",
    "dfcrdtr",
    "dfloaddt",
    "dforigamt",
    "dfcub",
    "dfstat",
    "dfsettlddate"
})
@XmlRootElement(name = "DEFAULT")
public class DEFAULT {

    @XmlElement(name = "DF_PRD", required = true)
    protected String dfprd;
    @XmlElement(name = "DF_CAPL")
    protected String dfcapl;
    @XmlElement(name = "DF_ACC_NO", required = true)
    protected String dfaccno;
    @XmlElement(name = "DF_CRDTR", required = true)
    protected String dfcrdtr;
    @XmlElement(name = "DF_LOAD_DT", required = true)
    protected String dfloaddt;
    @XmlElement(name = "DF_ORIG_AMT", required = true)
    protected String dforigamt;
    @XmlElement(name = "DF_CUB", required = true)
    protected String dfcub;
    @XmlElement(name = "DF_STAT", required = true)
    protected String dfstat;
    @XmlElement(name = "DF_SETTLD_DATE", required = true)
    protected String dfsettlddate;

    /**
     * Gets the value of the dfprd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFPRD() {
        return dfprd;
    }

    /**
     * Sets the value of the dfprd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFPRD(String value) {
        this.dfprd = value;
    }

    /**
     * Gets the value of the dfcapl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFCAPL() {
        return dfcapl;
    }

    /**
     * Sets the value of the dfcapl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFCAPL(String value) {
        this.dfcapl = value;
    }

    /**
     * Gets the value of the dfaccno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFACCNO() {
        return dfaccno;
    }

    /**
     * Sets the value of the dfaccno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFACCNO(String value) {
        this.dfaccno = value;
    }

    /**
     * Gets the value of the dfcrdtr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFCRDTR() {
        return dfcrdtr;
    }

    /**
     * Sets the value of the dfcrdtr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFCRDTR(String value) {
        this.dfcrdtr = value;
    }

    /**
     * Gets the value of the dfloaddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFLOADDT() {
        return dfloaddt;
    }

    /**
     * Sets the value of the dfloaddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFLOADDT(String value) {
        this.dfloaddt = value;
    }

    /**
     * Gets the value of the dforigamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFORIGAMT() {
        return dforigamt;
    }

    /**
     * Sets the value of the dforigamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFORIGAMT(String value) {
        this.dforigamt = value;
    }

    /**
     * Gets the value of the dfcub property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFCUB() {
        return dfcub;
    }

    /**
     * Sets the value of the dfcub property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFCUB(String value) {
        this.dfcub = value;
    }

    /**
     * Gets the value of the dfstat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFSTAT() {
        return dfstat;
    }

    /**
     * Sets the value of the dfstat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFSTAT(String value) {
        this.dfstat = value;
    }

    /**
     * Gets the value of the dfsettlddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFSETTLDDATE() {
        return dfsettlddate;
    }

    /**
     * Sets the value of the dfsettlddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFSETTLDDATE(String value) {
        this.dfsettlddate = value;
    }

}
