package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EADT" minOccurs="0"/>
 *         &lt;element ref="{}EAD1A" minOccurs="0"/>
 *         &lt;element ref="{}EAD2A" minOccurs="0"/>
 *         &lt;element ref="{}EAD1E" minOccurs="0"/>
 *         &lt;element ref="{}EAD2E" minOccurs="0"/>
 *         &lt;element ref="{}EAD6" minOccurs="0"/>
 *         &lt;element ref="{}EAD7" minOccurs="0"/>
 *         &lt;element ref="{}EAD8A" minOccurs="0"/>
 *         &lt;element ref="{}EAD8E" minOccurs="0"/>
 *         &lt;element ref="{}EAD9" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eadt",
    "ead1A",
    "ead2A",
    "ead1E",
    "ead2E",
    "ead6",
    "ead7",
    "ead8A",
    "ead8E",
    "ead9"
})
@XmlRootElement(name = "EADR")
public class EADR {

    @XmlElement(name = "EADT")
    protected String eadt;
    @XmlElement(name = "EAD1A")
    protected EAD1A ead1A;
    @XmlElement(name = "EAD2A")
    protected EAD2A ead2A;
    @XmlElement(name = "EAD1E")
    protected String ead1E;
    @XmlElement(name = "EAD2E")
    protected Object ead2E;
    @XmlElement(name = "EAD6")
    protected String ead6;
    @XmlElement(name = "EAD7")
    protected String ead7;
    @XmlElement(name = "EAD8A")
    protected EAD8A ead8A;
    @XmlElement(name = "EAD8E")
    protected String ead8E;
    @XmlElement(name = "EAD9")
    protected String ead9;

    /**
     * Gets the value of the eadt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEADT() {
        return eadt;
    }

    /**
     * Sets the value of the eadt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEADT(String value) {
        this.eadt = value;
    }

    /**
     * Gets the value of the ead1A property.
     * 
     * @return
     *     possible object is
     *     {@link EAD1A }
     *     
     */
    public EAD1A getEAD1A() {
        return ead1A;
    }

    /**
     * Sets the value of the ead1A property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAD1A }
     *     
     */
    public void setEAD1A(EAD1A value) {
        this.ead1A = value;
    }

    /**
     * Gets the value of the ead2A property.
     * 
     * @return
     *     possible object is
     *     {@link EAD2A }
     *     
     */
    public EAD2A getEAD2A() {
        return ead2A;
    }

    /**
     * Sets the value of the ead2A property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAD2A }
     *     
     */
    public void setEAD2A(EAD2A value) {
        this.ead2A = value;
    }

    /**
     * Gets the value of the ead1E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEAD1E() {
        return ead1E;
    }

    /**
     * Sets the value of the ead1E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEAD1E(String value) {
        this.ead1E = value;
    }

    /**
     * Gets the value of the ead2E property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEAD2E() {
        return ead2E;
    }

    /**
     * Sets the value of the ead2E property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEAD2E(Object value) {
        this.ead2E = value;
    }

    /**
     * Gets the value of the ead6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEAD6() {
        return ead6;
    }

    /**
     * Sets the value of the ead6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEAD6(String value) {
        this.ead6 = value;
    }

    /**
     * Gets the value of the ead7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEAD7() {
        return ead7;
    }

    /**
     * Sets the value of the ead7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEAD7(String value) {
        this.ead7 = value;
    }

    /**
     * Gets the value of the ead8A property.
     * 
     * @return
     *     possible object is
     *     {@link EAD8A }
     *     
     */
    public EAD8A getEAD8A() {
        return ead8A;
    }

    /**
     * Sets the value of the ead8A property.
     * 
     * @param value
     *     allowed object is
     *     {@link EAD8A }
     *     
     */
    public void setEAD8A(EAD8A value) {
        this.ead8A = value;
    }

    /**
     * Gets the value of the ead8E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEAD8E() {
        return ead8E;
    }

    /**
     * Sets the value of the ead8E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEAD8E(String value) {
        this.ead8E = value;
    }

    /**
     * Gets the value of the ead9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEAD9() {
        return ead9;
    }

    /**
     * Sets the value of the ead9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEAD9(String value) {
        this.ead9 = value;
    }

}
