package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CONSUMER_SEQ" minOccurs="0"/>
 *         &lt;element ref="{}FIELD"/>
 *         &lt;element ref="{}RSP_MSG"/>
 *         &lt;element ref="{}DATA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consumerseq",
    "field",
    "rspmsg",
    "data"
})
@XmlRootElement(name = "ERROR")
public class ERROR {

    @XmlElement(name = "CONSUMER_SEQ")
    protected String consumerseq;
    @XmlElement(name = "FIELD", required = true)
    protected String field;
    @XmlElement(name = "RSP_MSG", required = true)
    protected String rspmsg;
    @XmlElement(name = "DATA", required = true)
    protected String data;

    /**
     * Gets the value of the consumerseq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONSUMERSEQ() {
        return consumerseq;
    }

    /**
     * Sets the value of the consumerseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONSUMERSEQ(String value) {
        this.consumerseq = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIELD() {
        return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIELD(String value) {
        this.field = value;
    }

    /**
     * Gets the value of the rspmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSPMSG() {
        return rspmsg;
    }

    /**
     * Sets the value of the rspmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSPMSG(String value) {
        this.rspmsg = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATA() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATA(String value) {
        this.data = value;
    }

}
