package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MEMBER_ID"/>
 *         &lt;element ref="{}USER_ID"/>
 *         &lt;element ref="{}RUN_NO"/>
 *         &lt;element ref="{}TOT_ITEMS"/>
 *         &lt;element ref="{}ERR_ITEMS"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memberid",
    "userid",
    "runno",
    "totitems",
    "erritems"
})
@XmlRootElement(name = "HEADER")
public class HEADER {

    @XmlElement(name = "MEMBER_ID", required = true)
    protected String memberid;
    @XmlElement(name = "USER_ID", required = true)
    protected String userid;
    @XmlElement(name = "RUN_NO", required = true)
    protected String runno;
    @XmlElement(name = "TOT_ITEMS", required = true)
    protected String totitems;
    @XmlElement(name = "ERR_ITEMS", required = true)
    protected String erritems;

    /**
     * Gets the value of the memberid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMEMBERID() {
        return memberid;
    }

    /**
     * Sets the value of the memberid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMEMBERID(String value) {
        this.memberid = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERID(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the runno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRUNNO() {
        return runno;
    }

    /**
     * Sets the value of the runno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRUNNO(String value) {
        this.runno = value;
    }

    /**
     * Gets the value of the totitems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTITEMS() {
        return totitems;
    }

    /**
     * Sets the value of the totitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTITEMS(String value) {
        this.totitems = value;
    }

    /**
     * Gets the value of the erritems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERRITEMS() {
        return erritems;
    }

    /**
     * Sets the value of the erritems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERRITEMS(String value) {
        this.erritems = value;
    }

}
