package simahResponse.to.csv.SimahResponseCSV.simah.response;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ENQUIRY_REFERENCE" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element ref="{}RSP_REPORT"/>
 *           &lt;sequence>
 *             &lt;element ref="{}ERROR" maxOccurs="unbounded"/>
 *             &lt;element ref="{}NO_ERRORS"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="seq" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enquiryreference",
    "rspreport",
    "error",
    "noerrors"
})
@XmlRootElement(name = "ITEM")
public class ITEM {

    @XmlElement(name = "ENQUIRY_REFERENCE")
    protected String enquiryreference;
    @XmlElement(name = "RSP_REPORT")
    protected RSPREPORT rspreport;
    @XmlElement(name = "ERROR")
    protected List<ERROR> error;
    @XmlElement(name = "NO_ERRORS")
    protected String noerrors;
    @XmlAttribute(name = "seq")
    protected String seq;

    /**
     * Gets the value of the enquiryreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENQUIRYREFERENCE() {
        return enquiryreference;
    }

    /**
     * Sets the value of the enquiryreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENQUIRYREFERENCE(String value) {
        this.enquiryreference = value;
    }

    /**
     * Gets the value of the rspreport property.
     * 
     * @return
     *     possible object is
     *     {@link RSPREPORT }
     *     
     */
    public RSPREPORT getRSPREPORT() {
        return rspreport;
    }

    /**
     * Sets the value of the rspreport property.
     * 
     * @param value
     *     allowed object is
     *     {@link RSPREPORT }
     *     
     */
    public void setRSPREPORT(RSPREPORT value) {
        this.rspreport = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getERROR().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ERROR }
     * 
     * 
     */
    public List<ERROR> getERROR() {
        if (error == null) {
            error = new ArrayList<ERROR>();
        }
        return this.error;
    }

    /**
     * Gets the value of the noerrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOERRORS() {
        return noerrors;
    }

    /**
     * Sets the value of the noerrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOERRORS(String value) {
        this.noerrors = value;
    }

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeq(String value) {
        this.seq = value;
    }

}
