//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EJ_ENFORCE_DATE"/>
 *         &lt;element ref="{}EJ_RES_NUMBER"/>
 *         &lt;element ref="{}EJ_EXEC_TYPE"/>
 *         &lt;element ref="{}EJ_CITY"/>
 *         &lt;element ref="{}EJ_COURT_CODE"/>
 *         &lt;element ref="{}EJ_CASE_NUMBER"/>
 *         &lt;element ref="{}EJ_DATE_LOADED"/>
 *         &lt;element ref="{}EJ_ORIG_CLAIM_AMT"/>
 *         &lt;element ref="{}EJ_CLAIM_AMT"/>
 *         &lt;element ref="{}EJ_STATUS"/>
 *         &lt;element ref="{}EJ_SETTLE_DATE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ejenforcedate",
    "ejresnumber",
    "ejexectype",
    "ejcity",
    "ejcourtcode",
    "ejcasenumber",
    "ejdateloaded",
    "ejorigclaimamt",
    "ejclaimamt",
    "ejstatus",
    "ejsettledate"
})
@XmlRootElement(name = "JUDGEMENT")
public class JUDGEMENT {

    @XmlElement(name = "EJ_ENFORCE_DATE", required = true)
    protected String ejenforcedate;
    @XmlElement(name = "EJ_RES_NUMBER", required = true)
    protected String ejresnumber;
    @XmlElement(name = "EJ_EXEC_TYPE", required = true)
    protected String ejexectype;
    @XmlElement(name = "EJ_CITY", required = true)
    protected String ejcity;
    @XmlElement(name = "EJ_COURT_CODE", required = true)
    protected String ejcourtcode;
    @XmlElement(name = "EJ_CASE_NUMBER", required = true)
    protected String ejcasenumber;
    @XmlElement(name = "EJ_DATE_LOADED", required = true)
    protected String ejdateloaded;
    @XmlElement(name = "EJ_ORIG_CLAIM_AMT", required = true)
    protected String ejorigclaimamt;
    @XmlElement(name = "EJ_CLAIM_AMT", required = true)
    protected String ejclaimamt;
    @XmlElement(name = "EJ_STATUS", required = true)
    protected String ejstatus;
    @XmlElement(name = "EJ_SETTLE_DATE", required = true)
    protected String ejsettledate;

    /**
     * Gets the value of the ejenforcedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJENFORCEDATE() {
        return ejenforcedate;
    }

    /**
     * Sets the value of the ejenforcedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJENFORCEDATE(String value) {
        this.ejenforcedate = value;
    }

    /**
     * Gets the value of the ejresnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJRESNUMBER() {
        return ejresnumber;
    }

    /**
     * Sets the value of the ejresnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJRESNUMBER(String value) {
        this.ejresnumber = value;
    }

    /**
     * Gets the value of the ejexectype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJEXECTYPE() {
        return ejexectype;
    }

    /**
     * Sets the value of the ejexectype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJEXECTYPE(String value) {
        this.ejexectype = value;
    }

    /**
     * Gets the value of the ejcity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJCITY() {
        return ejcity;
    }

    /**
     * Sets the value of the ejcity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJCITY(String value) {
        this.ejcity = value;
    }

    /**
     * Gets the value of the ejcourtcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJCOURTCODE() {
        return ejcourtcode;
    }

    /**
     * Sets the value of the ejcourtcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJCOURTCODE(String value) {
        this.ejcourtcode = value;
    }

    /**
     * Gets the value of the ejcasenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJCASENUMBER() {
        return ejcasenumber;
    }

    /**
     * Sets the value of the ejcasenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJCASENUMBER(String value) {
        this.ejcasenumber = value;
    }

    /**
     * Gets the value of the ejdateloaded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJDATELOADED() {
        return ejdateloaded;
    }

    /**
     * Sets the value of the ejdateloaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJDATELOADED(String value) {
        this.ejdateloaded = value;
    }

    /**
     * Gets the value of the ejorigclaimamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJORIGCLAIMAMT() {
        return ejorigclaimamt;
    }

    /**
     * Sets the value of the ejorigclaimamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJORIGCLAIMAMT(String value) {
        this.ejorigclaimamt = value;
    }

    /**
     * Gets the value of the ejclaimamt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJCLAIMAMT() {
        return ejclaimamt;
    }

    /**
     * Sets the value of the ejclaimamt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJCLAIMAMT(String value) {
        this.ejclaimamt = value;
    }

    /**
     * Gets the value of the ejstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJSTATUS() {
        return ejstatus;
    }

    /**
     * Sets the value of the ejstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJSTATUS(String value) {
        this.ejstatus = value;
    }

    /**
     * Gets the value of the ejsettledate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEJSETTLEDATE() {
        return ejsettledate;
    }

    /**
     * Sets the value of the ejsettledate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEJSETTLEDATE(String value) {
        this.ejsettledate = value;
    }

}
