//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}NA_LOAD_DT"/>
 *         &lt;element ref="{}NA_LOADED_BY"/>
 *         &lt;element ref="{}NA_TYPE"/>
 *         &lt;element ref="{}NA_TEXT" minOccurs="0"/>
 *         &lt;element ref="{}NA_TEXT_AR" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "naloaddt",
    "naloadedby",
    "natype",
    "natext",
    "natextar"
})
@XmlRootElement(name = "NARRATIVE")
public class NARRATIVE {

    @XmlElement(name = "NA_LOAD_DT", required = true)
    protected String naloaddt;
    @XmlElement(name = "NA_LOADED_BY", required = true)
    protected String naloadedby;
    @XmlElement(name = "NA_TYPE", required = true)
    protected String natype;
    @XmlElement(name = "NA_TEXT")
    protected String natext;
    @XmlElement(name = "NA_TEXT_AR")
    protected NATEXTAR natextar;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the naloaddt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNALOADDT() {
        return naloaddt;
    }

    /**
     * Sets the value of the naloaddt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNALOADDT(String value) {
        this.naloaddt = value;
    }

    /**
     * Gets the value of the naloadedby property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNALOADEDBY() {
        return naloadedby;
    }

    /**
     * Sets the value of the naloadedby property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNALOADEDBY(String value) {
        this.naloadedby = value;
    }

    /**
     * Gets the value of the natype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATYPE() {
        return natype;
    }

    /**
     * Sets the value of the natype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATYPE(String value) {
        this.natype = value;
    }

    /**
     * Gets the value of the natext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATEXT() {
        return natext;
    }

    /**
     * Sets the value of the natext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATEXT(String value) {
        this.natext = value;
    }

    /**
     * Gets the value of the natextar property.
     * 
     * @return
     *     possible object is
     *     {@link NATEXTAR }
     *     
     */
    public NATEXTAR getNATEXTAR() {
        return natextar;
    }

    /**
     * Sets the value of the natextar property.
     * 
     * @param value
     *     allowed object is
     *     {@link NATEXTAR }
     *     
     */
    public void setNATEXTAR(NATEXTAR value) {
        this.natextar = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
