//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.channelvas.tamam.xtracash.darwin.mediation.simah.enquiry.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _TOTLIAB_QNAME = new QName("", "TOT_LIAB");
    private static final QName _PRCDPT_QNAME = new QName("", "PRCDPT");
    private static final QName _CISTATUS_QNAME = new QName("", "CI_STATUS");
    private static final QName _ACDOB_QNAME = new QName("", "ACDOB");
    private static final QName _USERID_QNAME = new QName("", "USER_ID");
    private static final QName _REQDATA_QNAME = new QName("", "REQ_DATA");
    private static final QName _EADT_QNAME = new QName("", "EADT");
    private static final QName _DFSTAT_QNAME = new QName("", "DF_STAT");
    private static final QName _EJCOURTCODE_QNAME = new QName("", "EJ_COURT_CODE");
    private static final QName _CIACCNO_QNAME = new QName("", "CI_ACC_NO");
    private static final QName _CACAD9_QNAME = new QName("", "CA_CAD9");
    private static final QName _CACAD7_QNAME = new QName("", "CA_CAD7");
    private static final QName _AMOUNT_QNAME = new QName("", "AMOUNT");
    private static final QName _ADVISORYTEXT_QNAME = new QName("", "ADVISORY_TEXT");
    private static final QName _CACAD2E_QNAME = new QName("", "CA_CAD2E");
    private static final QName _CACAD6_QNAME = new QName("", "CA_CAD6");
    private static final QName _CCN5_QNAME = new QName("", "CCN5");
    private static final QName _CCN4_QNAME = new QName("", "CCN4");
    private static final QName _CCN3_QNAME = new QName("", "CCN3");
    private static final QName _CCN2_QNAME = new QName("", "CCN2");
    private static final QName _EJRESNUMBER_QNAME = new QName("", "EJ_RES_NUMBER");
    private static final QName _CCN1_QNAME = new QName("", "CCN1");
    private static final QName _PEINQR_QNAME = new QName("", "PE_INQR");
    private static final QName _ENME_QNAME = new QName("", "ENME");
    private static final QName _FIELD_QNAME = new QName("", "FIELD");
    private static final QName _ETYP_QNAME = new QName("", "ETYP");
    private static final QName _CIFRQ_QNAME = new QName("", "CI_FRQ");
    private static final QName _CACADT_QNAME = new QName("", "CA_CADT");
    private static final QName _ACNM3E_QNAME = new QName("", "ACNM3E");
    private static final QName _ACNAT_QNAME = new QName("", "ACNAT");
    private static final QName _PENM1E_QNAME = new QName("", "PE_NM1E");
    private static final QName _EAD6_QNAME = new QName("", "EAD6");
    private static final QName _EAD7_QNAME = new QName("", "EAD7");
    private static final QName _PNCOMMENT_QNAME = new QName("", "PN_COMMENT");
    private static final QName _EJORIGCLAIMAMT_QNAME = new QName("", "EJ_ORIG_CLAIM_AMT");
    private static final QName _EAD9_QNAME = new QName("", "EAD9");
    private static final QName _CIODB_QNAME = new QName("", "CI_ODB");
    private static final QName _CICUB_QNAME = new QName("", "CI_CUB");
    private static final QName _PEAMOUNT_QNAME = new QName("", "PE_AMOUNT");
    private static final QName _BCCRDTR_QNAME = new QName("", "BC_CRDTR");
    private static final QName _NATYPE_QNAME = new QName("", "NA_TYPE");
    private static final QName _CITNR_QNAME = new QName("", "CI_TNR");
    private static final QName _TOTGLIAB_QNAME = new QName("", "TOT_GLIAB");
    private static final QName _DFCRDTR_QNAME = new QName("", "DF_CRDTR");
    private static final QName _CISUMMRY_QNAME = new QName("", "CI_SUMMRY");
    private static final QName _PEPRD_QNAME = new QName("", "PE_PRD");
    private static final QName _ENQUIRYNO_QNAME = new QName("", "ENQUIRY_NO");
    private static final QName _ENQRSN_QNAME = new QName("", "ENQRSN");
    private static final QName _CID3_QNAME = new QName("", "CID3");
    private static final QName _NATEXT_QNAME = new QName("", "NA_TEXT");
    private static final QName _CID2_QNAME = new QName("", "CID2");
    private static final QName _CID1_QNAME = new QName("", "CID1");
    private static final QName _PENM2E_QNAME = new QName("", "PE_NM2E");
    private static final QName _TOTLIM_QNAME = new QName("", "TOT_LIM");
    private static final QName _CICRDTR_QNAME = new QName("", "CI_CRDTR");
    private static final QName _CNTMTDE_QNAME = new QName("", "CNT_MTDE");
    private static final QName _DFPRD_QNAME = new QName("", "DF_PRD");
    private static final QName _DFACCNO_QNAME = new QName("", "DF_ACC_NO");
    private static final QName _PCEML_QNAME = new QName("", "PCEML");
    private static final QName _PETYPE_QNAME = new QName("", "PE_TYPE");
    private static final QName _VERSIONNO_QNAME = new QName("", "VERSION_NO");
    private static final QName _CACAD8E_QNAME = new QName("", "CA_CAD8E");
    private static final QName _CISEC_QNAME = new QName("", "CI_SEC");
    private static final QName _ACNMFE_QNAME = new QName("", "ACNMFE");
    private static final QName _BCCHECKNO_QNAME = new QName("", "BC_CHECK_NO");
    private static final QName _CONSUMERSEQ_QNAME = new QName("", "CONSUMER_SEQ");
    private static final QName _ACGND_QNAME = new QName("", "ACGND");
    private static final QName _DFLOADDT_QNAME = new QName("", "DF_LOAD_DT");
    private static final QName _PCNMFE_QNAME = new QName("", "PCNMFE");
    private static final QName _PENM3E_QNAME = new QName("", "PE_NM3E");
    private static final QName _EJCITY_QNAME = new QName("", "EJ_CITY");
    private static final QName _SCERROR_QNAME = new QName("", "SC_ERROR");
    private static final QName _CNTPE_QNAME = new QName("", "CNT_PE");
    private static final QName _NOOFAPPLICANTS_QNAME = new QName("", "NO_OF_APPLICANTS");
    private static final QName _BCCUB_QNAME = new QName("", "BC_CUB");
    private static final QName _ACMAR_QNAME = new QName("", "ACMAR");
    private static final QName _PNLOADDT_QNAME = new QName("", "PN_LOAD_DT");
    private static final QName _CICLSDDT_QNAME = new QName("", "CI_CLSD_DT");
    private static final QName _CINXTDUDT_QNAME = new QName("", "CI_NXT_DU_DT");
    private static final QName _CIINSTL_QNAME = new QName("", "CI_INSTL");
    private static final QName _CACAD1E_QNAME = new QName("", "CA_CAD1E");
    private static final QName _EDLD_QNAME = new QName("", "EDLD");
    private static final QName _EJENFORCEDATE_QNAME = new QName("", "EJ_ENFORCE_DATE");
    private static final QName _SCMINIMUM_QNAME = new QName("", "SC_MINIMUM");
    private static final QName _SCSCOREINDEX_QNAME = new QName("", "SC_SCOREINDEX");
    private static final QName _SCMAXIMUM_QNAME = new QName("", "SC_MAXIMUM");
    private static final QName _PNPUBLICATION_QNAME = new QName("", "PN_PUBLICATION");
    private static final QName _CILIMIT_QNAME = new QName("", "CI_LIMIT");
    private static final QName _DFCAPL_QNAME = new QName("", "DF_CAPL");
    private static final QName _BCSTAT_QNAME = new QName("", "BC_STAT");
    private static final QName _CIISSUDT_QNAME = new QName("", "CI_ISSU_DT");
    private static final QName _REPORTDATE_QNAME = new QName("", "REPORT_DATE");
    private static final QName _NOERRORS_QNAME = new QName("", "NO_ERRORS");
    private static final QName _CIMSG_QNAME = new QName("", "CI_MSG");
    private static final QName _EAD2E_QNAME = new QName("", "EAD2E");
    private static final QName _STATUS_QNAME = new QName("", "STATUS");
    private static final QName _EJSTATUS_QNAME = new QName("", "EJ_STATUS");
    private static final QName _EDOE_QNAME = new QName("", "EDOE");
    private static final QName _SCREASONCODE_QNAME = new QName("", "SC_REASON_CODE");
    private static final QName _SERVICE_QNAME = new QName("", "SERVICE");
    private static final QName _EJCLAIMAMT_QNAME = new QName("", "EJ_CLAIM_AMT");
    private static final QName _PCNM2E_QNAME = new QName("", "PCNM2E");
    private static final QName _BCORIGAMT_QNAME = new QName("", "BC_ORIG_AMT");
    private static final QName _PERSN_QNAME = new QName("", "PE_RSN");
    private static final QName _EIID_QNAME = new QName("", "EIID");
    private static final QName _RSPMSG_QNAME = new QName("", "RSP_MSG");
    private static final QName _PCNAT_QNAME = new QName("", "PCNAT");
    private static final QName _EJDATELOADED_QNAME = new QName("", "EJ_DATE_LOADED");
    private static final QName _CIPRD_QNAME = new QName("", "CI_PRD");
    private static final QName _EOCE_QNAME = new QName("", "EOCE");
    private static final QName _CALOADDT_QNAME = new QName("", "CA_LOAD_DT");
    private static final QName _TOTGLIM_QNAME = new QName("", "TOT_GLIM");
    private static final QName _ACNM7E_QNAME = new QName("", "ACNM7E");
    private static final QName _ELEN_QNAME = new QName("", "ELEN");
    private static final QName _PEDATE_QNAME = new QName("", "PE_DATE");
    private static final QName _CILASTPAYDT_QNAME = new QName("", "CI_LAST_PAY_DT");
    private static final QName _DATA_QNAME = new QName("", "DATA");
    private static final QName _PNTYPE_QNAME = new QName("", "PN_TYPE");
    private static final QName _ETMS_QNAME = new QName("", "ETMS");
    private static final QName _EAD1E_QNAME = new QName("", "EAD1E");
    private static final QName _MBRTYPE_QNAME = new QName("", "MBR_TYPE");
    private static final QName _PCNM3E_QNAME = new QName("", "PCNM3E");
    private static final QName _DITEXT_QNAME = new QName("", "DI_TEXT");
    private static final QName _ERRITEMS_QNAME = new QName("", "ERR_ITEMS");
    private static final QName _MBRSTS_QNAME = new QName("", "MBR_STS");
    private static final QName _PCDOB_QNAME = new QName("", "PCDOB");
    private static final QName _ACCOUNTTYPE_QNAME = new QName("", "ACCOUNT_TYPE");
    private static final QName _DFCUB_QNAME = new QName("", "DF_CUB");
    private static final QName _CAPL_QNAME = new QName("", "CAPL");
    private static final QName _CVIP_QNAME = new QName("", "CVIP");
    private static final QName _EJSETTLEDATE_QNAME = new QName("", "EJ_SETTLE_DATE");
    private static final QName _CNTDEF_QNAME = new QName("", "CNT_DEF");
    private static final QName _ENQUIRYREFERENCE_QNAME = new QName("", "ENQUIRY_REFERENCE");
    private static final QName _ACNM2E_QNAME = new QName("", "ACNM2E");
    private static final QName _CIPRODEXPDT_QNAME = new QName("", "CI_PROD_EXP_DT");
    private static final QName _EJCASENUMBER_QNAME = new QName("", "EJ_CASE_NUMBER");
    private static final QName _PEMEMBREF_QNAME = new QName("", "PE_MEMB_REF");
    private static final QName _BCLOADDT_QNAME = new QName("", "BC_LOAD_DT");
    private static final QName _NALOADDT_QNAME = new QName("", "NA_LOAD_DT");
    private static final QName _CNTGCI_QNAME = new QName("", "CNT_GCI");
    private static final QName _EJEXECTYPE_QNAME = new QName("", "EJ_EXEC_TYPE");
    private static final QName _ENTITY_QNAME = new QName("", "ENTITY");
    private static final QName _SCSCORE_QNAME = new QName("", "SC_SCORE");
    private static final QName _CURDB_QNAME = new QName("", "CUR_DB");
    private static final QName _RUNNO_QNAME = new QName("", "RUN_NO");
    private static final QName _PENMFE_QNAME = new QName("", "PE_NMFE");
    private static final QName _EMBS_QNAME = new QName("", "EMBS");
    private static final QName _CNTCI_QNAME = new QName("", "CNT_CI");
    private static final QName _DFORIGAMT_QNAME = new QName("", "DF_ORIG_AMT");
    private static final QName _EAD8E_QNAME = new QName("", "EAD8E");
    private static final QName _TOTITEMS_QNAME = new QName("", "TOT_ITEMS");
    private static final QName _CISAL_QNAME = new QName("", "CI_SAL");
    private static final QName _CILASTAMTPD_QNAME = new QName("", "CI_LAST_AMT_PD");
    private static final QName _ENQUIRYTYPE_QNAME = new QName("", "ENQUIRY_TYPE");
    private static final QName _ACNM1E_QNAME = new QName("", "ACNM1E");
    private static final QName _FICOG4_QNAME = new QName("", "FICOG4");
    private static final QName _SCSCORECARD_QNAME = new QName("", "SC_SCORECARD");
    private static final QName _PCGND_QNAME = new QName("", "PCGND");
    private static final QName _PCMAR_QNAME = new QName("", "PCMAR");
    private static final QName _BCSETTLDDATE_QNAME = new QName("", "BC_SETTLD_DATE");
    private static final QName _NALOADEDBY_QNAME = new QName("", "NA_LOADED_BY");
    private static final QName _PRODUCTTYPE_QNAME = new QName("", "PRODUCT_TYPE");
    private static final QName _ACEML_QNAME = new QName("", "ACEML");
    private static final QName _ECEX_QNAME = new QName("", "ECEX");
    private static final QName _ACTION_QNAME = new QName("", "ACTION");
    private static final QName _DFSETTLDDATE_QNAME = new QName("", "DF_SETTLD_DATE");
    private static final QName _BCPRD_QNAME = new QName("", "BC_PRD");
    private static final QName _MEMBERID_QNAME = new QName("", "MEMBER_ID");
    private static final QName _TOTDEF_QNAME = new QName("", "TOT_DEF");
    private static final QName _CIASOFDT_QNAME = new QName("", "CI_AS_OF_DT");
    private static final QName _PCNM1E_QNAME = new QName("", "PCNM1E");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.channelvas.tamam.xtracash.darwin.mediation.simah.enquiry.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EADR }
     * 
     */
    public EADR createEADR() {
        return new EADR();
    }

    /**
     * Create an instance of {@link EAD1A }
     * 
     */
    public EAD1A createEAD1A() {
        return new EAD1A();
    }

    /**
     * Create an instance of {@link EAD2A }
     * 
     */
    public EAD2A createEAD2A() {
        return new EAD2A();
    }

    /**
     * Create an instance of {@link EAD8A }
     * 
     */
    public EAD8A createEAD8A() {
        return new EAD8A();
    }

    /**
     * Create an instance of {@link SCREASONCODES }
     * 
     */
    public SCREASONCODES createSCREASONCODES() {
        return new SCREASONCODES();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

    /**
     * Create an instance of {@link RESPONSE }
     * 
     */
    public RESPONSE createRESPONSE() {
        return new RESPONSE();
    }

    /**
     * Create an instance of {@link HEADER }
     * 
     */
    public HEADER createHEADER() {
        return new HEADER();
    }

    /**
     * Create an instance of {@link MESSAGE }
     * 
     */
    public MESSAGE createMESSAGE() {
        return new MESSAGE();
    }

    /**
     * Create an instance of {@link ITEM }
     * 
     */
    public ITEM createITEM() {
        return new ITEM();
    }

    /**
     * Create an instance of {@link RSPREPORT }
     * 
     */
    public RSPREPORT createRSPREPORT() {
        return new RSPREPORT();
    }

    /**
     * Create an instance of {@link CONSUMER }
     * 
     */
    public CONSUMER createCONSUMER() {
        return new CONSUMER();
    }

    /**
     * Create an instance of {@link CID }
     * 
     */
    public CID createCID() {
        return new CID();
    }

    /**
     * Create an instance of {@link PROVIDED }
     * 
     */
    public PROVIDED createPROVIDED() {
        return new PROVIDED();
    }

    /**
     * Create an instance of {@link PCNAM }
     * 
     */
    public PCNAM createPCNAM() {
        return new PCNAM();
    }

    /**
     * Create an instance of {@link PCNMFA }
     * 
     */
    public PCNMFA createPCNMFA() {
        return new PCNMFA();
    }

    /**
     * Create an instance of {@link PCNM1A }
     * 
     */
    public PCNM1A createPCNM1A() {
        return new PCNM1A();
    }

    /**
     * Create an instance of {@link PCNM2A }
     * 
     */
    public PCNM2A createPCNM2A() {
        return new PCNM2A();
    }

    /**
     * Create an instance of {@link PCNM3A }
     * 
     */
    public PCNM3A createPCNM3A() {
        return new PCNM3A();
    }

    /**
     * Create an instance of {@link AVAILABLE }
     * 
     */
    public AVAILABLE createAVAILABLE() {
        return new AVAILABLE();
    }

    /**
     * Create an instance of {@link ACNAM }
     * 
     */
    public ACNAM createACNAM() {
        return new ACNAM();
    }

    /**
     * Create an instance of {@link ACNMFA }
     * 
     */
    public ACNMFA createACNMFA() {
        return new ACNMFA();
    }

    /**
     * Create an instance of {@link ACNM1A }
     * 
     */
    public ACNM1A createACNM1A() {
        return new ACNM1A();
    }

    /**
     * Create an instance of {@link ACNM2A }
     * 
     */
    public ACNM2A createACNM2A() {
        return new ACNM2A();
    }

    /**
     * Create an instance of {@link ACNM3A }
     * 
     */
    public ACNM3A createACNM3A() {
        return new ACNM3A();
    }

    /**
     * Create an instance of {@link ACNM7A }
     * 
     */
    public ACNM7A createACNM7A() {
        return new ACNM7A();
    }

    /**
     * Create an instance of {@link PREVENQUIRIES }
     * 
     */
    public PREVENQUIRIES createPREVENQUIRIES() {
        return new PREVENQUIRIES();
    }

    /**
     * Create an instance of {@link PREVENQUIRY }
     * 
     */
    public PREVENQUIRY createPREVENQUIRY() {
        return new PREVENQUIRY();
    }

    /**
     * Create an instance of {@link PENAME }
     * 
     */
    public PENAME createPENAME() {
        return new PENAME();
    }

    /**
     * Create an instance of {@link PENMFA }
     * 
     */
    public PENMFA createPENMFA() {
        return new PENMFA();
    }

    /**
     * Create an instance of {@link PENM1A }
     * 
     */
    public PENM1A createPENM1A() {
        return new PENM1A();
    }

    /**
     * Create an instance of {@link PENM2A }
     * 
     */
    public PENM2A createPENM2A() {
        return new PENM2A();
    }

    /**
     * Create an instance of {@link PENM3A }
     * 
     */
    public PENM3A createPENM3A() {
        return new PENM3A();
    }

    /**
     * Create an instance of {@link CIDETAILS }
     * 
     */
    public CIDETAILS createCIDETAILS() {
        return new CIDETAILS();
    }

    /**
     * Create an instance of {@link CIDETAIL }
     * 
     */
    public CIDETAIL createCIDETAIL() {
        return new CIDETAIL();
    }

    /**
     * Create an instance of {@link DEFAULTS }
     * 
     */
    public DEFAULTS createDEFAULTS() {
        return new DEFAULTS();
    }

    /**
     * Create an instance of {@link DEFAULT }
     * 
     */
    public DEFAULT createDEFAULT() {
        return new DEFAULT();
    }

    /**
     * Create an instance of {@link BOUNCEDCHECKS }
     * 
     */
    public BOUNCEDCHECKS createBOUNCEDCHECKS() {
        return new BOUNCEDCHECKS();
    }

    /**
     * Create an instance of {@link BOUNCEDCHECK }
     * 
     */
    public BOUNCEDCHECK createBOUNCEDCHECK() {
        return new BOUNCEDCHECK();
    }

    /**
     * Create an instance of {@link PUBLICNOTICES }
     * 
     */
    public PUBLICNOTICES createPUBLICNOTICES() {
        return new PUBLICNOTICES();
    }

    /**
     * Create an instance of {@link PUBLICNOTICE }
     * 
     */
    public PUBLICNOTICE createPUBLICNOTICE() {
        return new PUBLICNOTICE();
    }

    /**
     * Create an instance of {@link PNPUBLICATIONAR }
     * 
     */
    public PNPUBLICATIONAR createPNPUBLICATIONAR() {
        return new PNPUBLICATIONAR();
    }

    /**
     * Create an instance of {@link PNCOMMENTAR }
     * 
     */
    public PNCOMMENTAR createPNCOMMENTAR() {
        return new PNCOMMENTAR();
    }

    /**
     * Create an instance of {@link JUDGEMENTS }
     * 
     */
    public JUDGEMENTS createJUDGEMENTS() {
        return new JUDGEMENTS();
    }

    /**
     * Create an instance of {@link JUDGEMENT }
     * 
     */
    public JUDGEMENT createJUDGEMENT() {
        return new JUDGEMENT();
    }

    /**
     * Create an instance of {@link NARRATIVES }
     * 
     */
    public NARRATIVES createNARRATIVES() {
        return new NARRATIVES();
    }

    /**
     * Create an instance of {@link NARRATIVE }
     * 
     */
    public NARRATIVE createNARRATIVE() {
        return new NARRATIVE();
    }

    /**
     * Create an instance of {@link NATEXTAR }
     * 
     */
    public NATEXTAR createNATEXTAR() {
        return new NATEXTAR();
    }

    /**
     * Create an instance of {@link ADDRESSES }
     * 
     */
    public ADDRESSES createADDRESSES() {
        return new ADDRESSES();
    }

    /**
     * Create an instance of {@link ADDRESS }
     * 
     */
    public ADDRESS createADDRESS() {
        return new ADDRESS();
    }

    /**
     * Create an instance of {@link CACAD1A }
     * 
     */
    public CACAD1A createCACAD1A() {
        return new CACAD1A();
    }

    /**
     * Create an instance of {@link CACAD2A }
     * 
     */
    public CACAD2A createCACAD2A() {
        return new CACAD2A();
    }

    /**
     * Create an instance of {@link CACAD8A }
     * 
     */
    public CACAD8A createCACAD8A() {
        return new CACAD8A();
    }

    /**
     * Create an instance of {@link CONTACTS }
     * 
     */
    public CONTACTS createCONTACTS() {
        return new CONTACTS();
    }

    /**
     * Create an instance of {@link CCNT }
     * 
     */
    public CCNT createCCNT() {
        return new CCNT();
    }

    /**
     * Create an instance of {@link EMPLOYERS }
     * 
     */
    public EMPLOYERS createEMPLOYERS() {
        return new EMPLOYERS();
    }

    /**
     * Create an instance of {@link EMPLOYER }
     * 
     */
    public EMPLOYER createEMPLOYER() {
        return new EMPLOYER();
    }

    /**
     * Create an instance of {@link ENMA }
     * 
     */
    public ENMA createENMA() {
        return new ENMA();
    }

    /**
     * Create an instance of {@link EOCA }
     * 
     */
    public EOCA createEOCA() {
        return new EOCA();
    }

    /**
     * Create an instance of {@link ADVISORYSUMMARYTEXT }
     * 
     */
    public ADVISORYSUMMARYTEXT createADVISORYSUMMARYTEXT() {
        return new ADVISORYSUMMARYTEXT();
    }

    /**
     * Create an instance of {@link SUMMARY }
     * 
     */
    public SUMMARY createSUMMARY() {
        return new SUMMARY();
    }

    /**
     * Create an instance of {@link SCORE }
     * 
     */
    public SCORE createSCORE() {
        return new SCORE();
    }

    /**
     * Create an instance of {@link DISCLAIMER }
     * 
     */
    public DISCLAIMER createDISCLAIMER() {
        return new DISCLAIMER();
    }

    /**
     * Create an instance of {@link DITEXTAR }
     * 
     */
    public DITEXTAR createDITEXTAR() {
        return new DITEXTAR();
    }

    /**
     * Create an instance of {@link PARSER }
     * 
     */
    public PARSER createPARSER() {
        return new PARSER();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_LIAB")
    public JAXBElement<String> createTOTLIAB(String value) {
        return new JAXBElement<>(_TOTLIAB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRCDPT")
    public JAXBElement<String> createPRCDPT(String value) {
        return new JAXBElement<>(_PRCDPT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_STATUS")
    public JAXBElement<String> createCISTATUS(String value) {
        return new JAXBElement<>(_CISTATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACDOB")
    public JAXBElement<String> createACDOB(String value) {
        return new JAXBElement<>(_ACDOB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "USER_ID")
    public JAXBElement<String> createUSERID(String value) {
        return new JAXBElement<>(_USERID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REQ_DATA")
    public JAXBElement<String> createREQDATA(String value) {
        return new JAXBElement<>(_REQDATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EADT")
    public JAXBElement<String> createEADT(String value) {
        return new JAXBElement<>(_EADT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_STAT")
    public JAXBElement<String> createDFSTAT(String value) {
        return new JAXBElement<>(_DFSTAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_COURT_CODE")
    public JAXBElement<String> createEJCOURTCODE(String value) {
        return new JAXBElement<>(_EJCOURTCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_ACC_NO")
    public JAXBElement<String> createCIACCNO(String value) {
        return new JAXBElement<>(_CIACCNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD9")
    public JAXBElement<String> createCACAD9(String value) {
        return new JAXBElement<>(_CACAD9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD7")
    public JAXBElement<String> createCACAD7(String value) {
        return new JAXBElement<>(_CACAD7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AMOUNT")
    public JAXBElement<String> createAMOUNT(String value) {
        return new JAXBElement<>(_AMOUNT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADVISORY_TEXT")
    public JAXBElement<Object> createADVISORYTEXT(Object value) {
        return new JAXBElement<>(_ADVISORYTEXT_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD2E")
    public JAXBElement<String> createCACAD2E(String value) {
        return new JAXBElement<>(_CACAD2E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD6")
    public JAXBElement<String> createCACAD6(String value) {
        return new JAXBElement<>(_CACAD6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CCN5")
    public JAXBElement<String> createCCN5(String value) {
        return new JAXBElement<>(_CCN5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CCN4")
    public JAXBElement<String> createCCN4(String value) {
        return new JAXBElement<>(_CCN4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CCN3")
    public JAXBElement<String> createCCN3(String value) {
        return new JAXBElement<>(_CCN3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CCN2")
    public JAXBElement<String> createCCN2(String value) {
        return new JAXBElement<>(_CCN2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_RES_NUMBER")
    public JAXBElement<String> createEJRESNUMBER(String value) {
        return new JAXBElement<>(_EJRESNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CCN1")
    public JAXBElement<String> createCCN1(String value) {
        return new JAXBElement<>(_CCN1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_INQR")
    public JAXBElement<String> createPEINQR(String value) {
        return new JAXBElement<>(_PEINQR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENME")
    public JAXBElement<String> createENME(String value) {
        return new JAXBElement<>(_ENME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIELD")
    public JAXBElement<String> createFIELD(String value) {
        return new JAXBElement<>(_FIELD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETYP")
    public JAXBElement<String> createETYP(String value) {
        return new JAXBElement<>(_ETYP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_FRQ")
    public JAXBElement<String> createCIFRQ(String value) {
        return new JAXBElement<>(_CIFRQ_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CADT")
    public JAXBElement<String> createCACADT(String value) {
        return new JAXBElement<>(_CACADT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNM3E")
    public JAXBElement<String> createACNM3E(String value) {
        return new JAXBElement<>(_ACNM3E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNAT")
    public JAXBElement<String> createACNAT(String value) {
        return new JAXBElement<>(_ACNAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_NM1E")
    public JAXBElement<String> createPENM1E(String value) {
        return new JAXBElement<>(_PENM1E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD6")
    public JAXBElement<String> createEAD6(String value) {
        return new JAXBElement<>(_EAD6_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD7")
    public JAXBElement<String> createEAD7(String value) {
        return new JAXBElement<>(_EAD7_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PN_COMMENT")
    public JAXBElement<String> createPNCOMMENT(String value) {
        return new JAXBElement<>(_PNCOMMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_ORIG_CLAIM_AMT")
    public JAXBElement<String> createEJORIGCLAIMAMT(String value) {
        return new JAXBElement<>(_EJORIGCLAIMAMT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD9")
    public JAXBElement<String> createEAD9(String value) {
        return new JAXBElement<>(_EAD9_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_ODB")
    public JAXBElement<String> createCIODB(String value) {
        return new JAXBElement<>(_CIODB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_CUB")
    public JAXBElement<String> createCICUB(String value) {
        return new JAXBElement<>(_CICUB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_AMOUNT")
    public JAXBElement<String> createPEAMOUNT(String value) {
        return new JAXBElement<>(_PEAMOUNT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_CRDTR")
    public JAXBElement<String> createBCCRDTR(String value) {
        return new JAXBElement<>(_BCCRDTR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NA_TYPE")
    public JAXBElement<String> createNATYPE(String value) {
        return new JAXBElement<>(_NATYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_TNR")
    public JAXBElement<String> createCITNR(String value) {
        return new JAXBElement<>(_CITNR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_GLIAB")
    public JAXBElement<String> createTOTGLIAB(String value) {
        return new JAXBElement<>(_TOTGLIAB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_CRDTR")
    public JAXBElement<String> createDFCRDTR(String value) {
        return new JAXBElement<>(_DFCRDTR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_SUMMRY")
    public JAXBElement<String> createCISUMMRY(String value) {
        return new JAXBElement<>(_CISUMMRY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_PRD")
    public JAXBElement<String> createPEPRD(String value) {
        return new JAXBElement<>(_PEPRD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENQUIRY_NO")
    public JAXBElement<String> createENQUIRYNO(String value) {
        return new JAXBElement<>(_ENQUIRYNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENQRSN")
    public JAXBElement<String> createENQRSN(String value) {
        return new JAXBElement<>(_ENQRSN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CID3")
    public JAXBElement<String> createCID3(String value) {
        return new JAXBElement<>(_CID3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NA_TEXT")
    public JAXBElement<String> createNATEXT(String value) {
        return new JAXBElement<>(_NATEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CID2")
    public JAXBElement<String> createCID2(String value) {
        return new JAXBElement<>(_CID2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CID1")
    public JAXBElement<String> createCID1(String value) {
        return new JAXBElement<>(_CID1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_NM2E")
    public JAXBElement<String> createPENM2E(String value) {
        return new JAXBElement<>(_PENM2E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_LIM")
    public JAXBElement<String> createTOTLIM(String value) {
        return new JAXBElement<>(_TOTLIM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_CRDTR")
    public JAXBElement<String> createCICRDTR(String value) {
        return new JAXBElement<>(_CICRDTR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CNT_MTDE")
    public JAXBElement<String> createCNTMTDE(String value) {
        return new JAXBElement<>(_CNTMTDE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_PRD")
    public JAXBElement<String> createDFPRD(String value) {
        return new JAXBElement<>(_DFPRD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_ACC_NO")
    public JAXBElement<String> createDFACCNO(String value) {
        return new JAXBElement<>(_DFACCNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCEML")
    public JAXBElement<String> createPCEML(String value) {
        return new JAXBElement<>(_PCEML_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_TYPE")
    public JAXBElement<String> createPETYPE(String value) {
        return new JAXBElement<>(_PETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VERSION_NO")
    public JAXBElement<String> createVERSIONNO(String value) {
        return new JAXBElement<>(_VERSIONNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD8E")
    public JAXBElement<String> createCACAD8E(String value) {
        return new JAXBElement<>(_CACAD8E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_SEC")
    public JAXBElement<String> createCISEC(String value) {
        return new JAXBElement<>(_CISEC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNMFE")
    public JAXBElement<String> createACNMFE(String value) {
        return new JAXBElement<>(_ACNMFE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_CHECK_NO")
    public JAXBElement<String> createBCCHECKNO(String value) {
        return new JAXBElement<>(_BCCHECKNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CONSUMER_SEQ")
    public JAXBElement<String> createCONSUMERSEQ(String value) {
        return new JAXBElement<>(_CONSUMERSEQ_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACGND")
    public JAXBElement<String> createACGND(String value) {
        return new JAXBElement<>(_ACGND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_LOAD_DT")
    public JAXBElement<String> createDFLOADDT(String value) {
        return new JAXBElement<>(_DFLOADDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCNMFE")
    public JAXBElement<String> createPCNMFE(String value) {
        return new JAXBElement<>(_PCNMFE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_NM3E")
    public JAXBElement<String> createPENM3E(String value) {
        return new JAXBElement<>(_PENM3E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_CITY")
    public JAXBElement<String> createEJCITY(String value) {
        return new JAXBElement<>(_EJCITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_ERROR")
    public JAXBElement<String> createSCERROR(String value) {
        return new JAXBElement<>(_SCERROR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CNT_PE")
    public JAXBElement<String> createCNTPE(String value) {
        return new JAXBElement<>(_CNTPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NO_OF_APPLICANTS")
    public JAXBElement<String> createNOOFAPPLICANTS(String value) {
        return new JAXBElement<>(_NOOFAPPLICANTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_CUB")
    public JAXBElement<String> createBCCUB(String value) {
        return new JAXBElement<>(_BCCUB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACMAR")
    public JAXBElement<String> createACMAR(String value) {
        return new JAXBElement<>(_ACMAR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PN_LOAD_DT")
    public JAXBElement<String> createPNLOADDT(String value) {
        return new JAXBElement<>(_PNLOADDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_CLSD_DT")
    public JAXBElement<String> createCICLSDDT(String value) {
        return new JAXBElement<>(_CICLSDDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_NXT_DU_DT")
    public JAXBElement<String> createCINXTDUDT(String value) {
        return new JAXBElement<>(_CINXTDUDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_INSTL")
    public JAXBElement<String> createCIINSTL(String value) {
        return new JAXBElement<>(_CIINSTL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_CAD1E")
    public JAXBElement<String> createCACAD1E(String value) {
        return new JAXBElement<>(_CACAD1E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EDLD")
    public JAXBElement<String> createEDLD(String value) {
        return new JAXBElement<>(_EDLD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_ENFORCE_DATE")
    public JAXBElement<String> createEJENFORCEDATE(String value) {
        return new JAXBElement<>(_EJENFORCEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_MINIMUM")
    public JAXBElement<String> createSCMINIMUM(String value) {
        return new JAXBElement<>(_SCMINIMUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_SCOREINDEX")
    public JAXBElement<String> createSCSCOREINDEX(String value) {
        return new JAXBElement<>(_SCSCOREINDEX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_MAXIMUM")
    public JAXBElement<String> createSCMAXIMUM(String value) {
        return new JAXBElement<>(_SCMAXIMUM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PN_PUBLICATION")
    public JAXBElement<String> createPNPUBLICATION(String value) {
        return new JAXBElement<>(_PNPUBLICATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_LIMIT")
    public JAXBElement<String> createCILIMIT(String value) {
        return new JAXBElement<>(_CILIMIT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_CAPL")
    public JAXBElement<String> createDFCAPL(String value) {
        return new JAXBElement<>(_DFCAPL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_STAT")
    public JAXBElement<String> createBCSTAT(String value) {
        return new JAXBElement<>(_BCSTAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_ISSU_DT")
    public JAXBElement<String> createCIISSUDT(String value) {
        return new JAXBElement<>(_CIISSUDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REPORT_DATE")
    public JAXBElement<String> createREPORTDATE(String value) {
        return new JAXBElement<>(_REPORTDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NO_ERRORS")
    public JAXBElement<String> createNOERRORS(String value) {
        return new JAXBElement<>(_NOERRORS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_MSG")
    public JAXBElement<String> createCIMSG(String value) {
        return new JAXBElement<>(_CIMSG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD2E")
    public JAXBElement<Object> createEAD2E(Object value) {
        return new JAXBElement<>(_EAD2E_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATUS")
    public JAXBElement<String> createSTATUS(String value) {
        return new JAXBElement<>(_STATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_STATUS")
    public JAXBElement<String> createEJSTATUS(String value) {
        return new JAXBElement<>(_EJSTATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EDOE")
    public JAXBElement<String> createEDOE(String value) {
        return new JAXBElement<>(_EDOE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_REASON_CODE")
    public JAXBElement<String> createSCREASONCODE(String value) {
        return new JAXBElement<>(_SCREASONCODE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SERVICE")
    public JAXBElement<String> createSERVICE(String value) {
        return new JAXBElement<>(_SERVICE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_CLAIM_AMT")
    public JAXBElement<String> createEJCLAIMAMT(String value) {
        return new JAXBElement<>(_EJCLAIMAMT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCNM2E")
    public JAXBElement<String> createPCNM2E(String value) {
        return new JAXBElement<>(_PCNM2E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_ORIG_AMT")
    public JAXBElement<String> createBCORIGAMT(String value) {
        return new JAXBElement<>(_BCORIGAMT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_RSN")
    public JAXBElement<String> createPERSN(String value) {
        return new JAXBElement<>(_PERSN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EIID")
    public JAXBElement<String> createEIID(String value) {
        return new JAXBElement<>(_EIID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RSP_MSG")
    public JAXBElement<String> createRSPMSG(String value) {
        return new JAXBElement<>(_RSPMSG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCNAT")
    public JAXBElement<String> createPCNAT(String value) {
        return new JAXBElement<>(_PCNAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_DATE_LOADED")
    public JAXBElement<String> createEJDATELOADED(String value) {
        return new JAXBElement<>(_EJDATELOADED_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_PRD")
    public JAXBElement<String> createCIPRD(String value) {
        return new JAXBElement<>(_CIPRD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EOCE")
    public JAXBElement<String> createEOCE(String value) {
        return new JAXBElement<>(_EOCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CA_LOAD_DT")
    public JAXBElement<String> createCALOADDT(String value) {
        return new JAXBElement<>(_CALOADDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_GLIM")
    public JAXBElement<String> createTOTGLIM(String value) {
        return new JAXBElement<>(_TOTGLIM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNM7E")
    public JAXBElement<String> createACNM7E(String value) {
        return new JAXBElement<>(_ACNM7E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ELEN")
    public JAXBElement<String> createELEN(String value) {
        return new JAXBElement<>(_ELEN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_DATE")
    public JAXBElement<String> createPEDATE(String value) {
        return new JAXBElement<>(_PEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_LAST_PAY_DT")
    public JAXBElement<String> createCILASTPAYDT(String value) {
        return new JAXBElement<>(_CILASTPAYDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DATA")
    public JAXBElement<String> createDATA(String value) {
        return new JAXBElement<>(_DATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PN_TYPE")
    public JAXBElement<String> createPNTYPE(String value) {
        return new JAXBElement<>(_PNTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ETMS")
    public JAXBElement<String> createETMS(String value) {
        return new JAXBElement<>(_ETMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD1E")
    public JAXBElement<String> createEAD1E(String value) {
        return new JAXBElement<>(_EAD1E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MBR_TYPE")
    public JAXBElement<String> createMBRTYPE(String value) {
        return new JAXBElement<>(_MBRTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCNM3E")
    public JAXBElement<String> createPCNM3E(String value) {
        return new JAXBElement<>(_PCNM3E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DI_TEXT")
    public JAXBElement<String> createDITEXT(String value) {
        return new JAXBElement<>(_DITEXT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ERR_ITEMS")
    public JAXBElement<String> createERRITEMS(String value) {
        return new JAXBElement<>(_ERRITEMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MBR_STS")
    public JAXBElement<String> createMBRSTS(String value) {
        return new JAXBElement<>(_MBRSTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCDOB")
    public JAXBElement<String> createPCDOB(String value) {
        return new JAXBElement<>(_PCDOB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACCOUNT_TYPE")
    public JAXBElement<String> createACCOUNTTYPE(String value) {
        return new JAXBElement<>(_ACCOUNTTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_CUB")
    public JAXBElement<String> createDFCUB(String value) {
        return new JAXBElement<>(_DFCUB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CAPL")
    public JAXBElement<String> createCAPL(String value) {
        return new JAXBElement<>(_CAPL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CVIP")
    public JAXBElement<String> createCVIP(String value) {
        return new JAXBElement<>(_CVIP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_SETTLE_DATE")
    public JAXBElement<String> createEJSETTLEDATE(String value) {
        return new JAXBElement<>(_EJSETTLEDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CNT_DEF")
    public JAXBElement<String> createCNTDEF(String value) {
        return new JAXBElement<>(_CNTDEF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENQUIRY_REFERENCE")
    public JAXBElement<String> createENQUIRYREFERENCE(String value) {
        return new JAXBElement<>(_ENQUIRYREFERENCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNM2E")
    public JAXBElement<String> createACNM2E(String value) {
        return new JAXBElement<>(_ACNM2E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_PROD_EXP_DT")
    public JAXBElement<String> createCIPRODEXPDT(String value) {
        return new JAXBElement<>(_CIPRODEXPDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_CASE_NUMBER")
    public JAXBElement<String> createEJCASENUMBER(String value) {
        return new JAXBElement<>(_EJCASENUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_MEMB_REF")
    public JAXBElement<String> createPEMEMBREF(String value) {
        return new JAXBElement<>(_PEMEMBREF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_LOAD_DT")
    public JAXBElement<String> createBCLOADDT(String value) {
        return new JAXBElement<>(_BCLOADDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NA_LOAD_DT")
    public JAXBElement<String> createNALOADDT(String value) {
        return new JAXBElement<>(_NALOADDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CNT_GCI")
    public JAXBElement<String> createCNTGCI(String value) {
        return new JAXBElement<>(_CNTGCI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EJ_EXEC_TYPE")
    public JAXBElement<String> createEJEXECTYPE(String value) {
        return new JAXBElement<>(_EJEXECTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENTITY")
    public JAXBElement<String> createENTITY(String value) {
        return new JAXBElement<>(_ENTITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_SCORE")
    public JAXBElement<String> createSCSCORE(String value) {
        return new JAXBElement<>(_SCSCORE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CUR_DB")
    public JAXBElement<String> createCURDB(String value) {
        return new JAXBElement<>(_CURDB_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RUN_NO")
    public JAXBElement<String> createRUNNO(String value) {
        return new JAXBElement<>(_RUNNO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PE_NMFE")
    public JAXBElement<String> createPENMFE(String value) {
        return new JAXBElement<>(_PENMFE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMBS")
    public JAXBElement<String> createEMBS(String value) {
        return new JAXBElement<>(_EMBS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CNT_CI")
    public JAXBElement<String> createCNTCI(String value) {
        return new JAXBElement<>(_CNTCI_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_ORIG_AMT")
    public JAXBElement<String> createDFORIGAMT(String value) {
        return new JAXBElement<>(_DFORIGAMT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EAD8E")
    public JAXBElement<String> createEAD8E(String value) {
        return new JAXBElement<>(_EAD8E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_ITEMS")
    public JAXBElement<String> createTOTITEMS(String value) {
        return new JAXBElement<>(_TOTITEMS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_SAL")
    public JAXBElement<String> createCISAL(String value) {
        return new JAXBElement<>(_CISAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_LAST_AMT_PD")
    public JAXBElement<String> createCILASTAMTPD(String value) {
        return new JAXBElement<>(_CILASTAMTPD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENQUIRY_TYPE")
    public JAXBElement<String> createENQUIRYTYPE(String value) {
        return new JAXBElement<>(_ENQUIRYTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACNM1E")
    public JAXBElement<String> createACNM1E(String value) {
        return new JAXBElement<>(_ACNM1E_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FICOG4")
    public JAXBElement<String> createFICOG4(String value) {
        return new JAXBElement<>(_FICOG4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SC_SCORECARD")
    public JAXBElement<String> createSCSCORECARD(String value) {
        return new JAXBElement<>(_SCSCORECARD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCGND")
    public JAXBElement<String> createPCGND(String value) {
        return new JAXBElement<>(_PCGND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCMAR")
    public JAXBElement<String> createPCMAR(String value) {
        return new JAXBElement<>(_PCMAR_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_SETTLD_DATE")
    public JAXBElement<String> createBCSETTLDDATE(String value) {
        return new JAXBElement<>(_BCSETTLDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NA_LOADED_BY")
    public JAXBElement<String> createNALOADEDBY(String value) {
        return new JAXBElement<>(_NALOADEDBY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PRODUCT_TYPE")
    public JAXBElement<String> createPRODUCTTYPE(String value) {
        return new JAXBElement<>(_PRODUCTTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACEML")
    public JAXBElement<String> createACEML(String value) {
        return new JAXBElement<>(_ACEML_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ECEX")
    public JAXBElement<String> createECEX(String value) {
        return new JAXBElement<>(_ECEX_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ACTION")
    public JAXBElement<String> createACTION(String value) {
        return new JAXBElement<>(_ACTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DF_SETTLD_DATE")
    public JAXBElement<String> createDFSETTLDDATE(String value) {
        return new JAXBElement<>(_DFSETTLDDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BC_PRD")
    public JAXBElement<String> createBCPRD(String value) {
        return new JAXBElement<>(_BCPRD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MEMBER_ID")
    public JAXBElement<String> createMEMBERID(String value) {
        return new JAXBElement<>(_MEMBERID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOT_DEF")
    public JAXBElement<String> createTOTDEF(String value) {
        return new JAXBElement<>(_TOTDEF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CI_AS_OF_DT")
    public JAXBElement<String> createCIASOFDT(String value) {
        return new JAXBElement<>(_CIASOFDT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCNM1E")
    public JAXBElement<String> createPCNM1E(String value) {
        return new JAXBElement<>(_PCNM1E_QNAME, String.class, null, value);
    }

}
