//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}RSP_MSG"/>
 *         &lt;element ref="{}REQ_DATA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rspmsg",
    "reqdata"
})
@XmlRootElement(name = "PARSER")
public class PARSER {

    @XmlElement(name = "RSP_MSG", required = true)
    protected String rspmsg;
    @XmlElement(name = "REQ_DATA", required = true)
    protected String reqdata;

    /**
     * Gets the value of the rspmsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRSPMSG() {
        return rspmsg;
    }

    /**
     * Sets the value of the rspmsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRSPMSG(String value) {
        this.rspmsg = value;
    }

    /**
     * Gets the value of the reqdata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREQDATA() {
        return reqdata;
    }

    /**
     * Sets the value of the reqdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREQDATA(String value) {
        this.reqdata = value;
    }

}
