//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PCNMFA" minOccurs="0"/>
 *         &lt;element ref="{}PCNM1A" minOccurs="0"/>
 *         &lt;element ref="{}PCNM2A" minOccurs="0"/>
 *         &lt;element ref="{}PCNM3A" minOccurs="0"/>
 *         &lt;element ref="{}PCNMFE" minOccurs="0"/>
 *         &lt;element ref="{}PCNM1E" minOccurs="0"/>
 *         &lt;element ref="{}PCNM2E" minOccurs="0"/>
 *         &lt;element ref="{}PCNM3E" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pcnmfa",
    "pcnm1A",
    "pcnm2A",
    "pcnm3A",
    "pcnmfe",
    "pcnm1E",
    "pcnm2E",
    "pcnm3E"
})
@XmlRootElement(name = "PCNAM")
public class PCNAM {

    @XmlElement(name = "PCNMFA")
    protected PCNMFA pcnmfa;
    @XmlElement(name = "PCNM1A")
    protected PCNM1A pcnm1A;
    @XmlElement(name = "PCNM2A")
    protected PCNM2A pcnm2A;
    @XmlElement(name = "PCNM3A")
    protected PCNM3A pcnm3A;
    @XmlElement(name = "PCNMFE")
    protected String pcnmfe;
    @XmlElement(name = "PCNM1E")
    protected String pcnm1E;
    @XmlElement(name = "PCNM2E")
    protected String pcnm2E;
    @XmlElement(name = "PCNM3E")
    protected String pcnm3E;

    /**
     * Gets the value of the pcnmfa property.
     * 
     * @return
     *     possible object is
     *     {@link PCNMFA }
     *     
     */
    public PCNMFA getPCNMFA() {
        return pcnmfa;
    }

    /**
     * Sets the value of the pcnmfa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCNMFA }
     *     
     */
    public void setPCNMFA(PCNMFA value) {
        this.pcnmfa = value;
    }

    /**
     * Gets the value of the pcnm1A property.
     * 
     * @return
     *     possible object is
     *     {@link PCNM1A }
     *     
     */
    public PCNM1A getPCNM1A() {
        return pcnm1A;
    }

    /**
     * Sets the value of the pcnm1A property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCNM1A }
     *     
     */
    public void setPCNM1A(PCNM1A value) {
        this.pcnm1A = value;
    }

    /**
     * Gets the value of the pcnm2A property.
     * 
     * @return
     *     possible object is
     *     {@link PCNM2A }
     *     
     */
    public PCNM2A getPCNM2A() {
        return pcnm2A;
    }

    /**
     * Sets the value of the pcnm2A property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCNM2A }
     *     
     */
    public void setPCNM2A(PCNM2A value) {
        this.pcnm2A = value;
    }

    /**
     * Gets the value of the pcnm3A property.
     * 
     * @return
     *     possible object is
     *     {@link PCNM3A }
     *     
     */
    public PCNM3A getPCNM3A() {
        return pcnm3A;
    }

    /**
     * Sets the value of the pcnm3A property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCNM3A }
     *     
     */
    public void setPCNM3A(PCNM3A value) {
        this.pcnm3A = value;
    }

    /**
     * Gets the value of the pcnmfe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCNMFE() {
        return pcnmfe;
    }

    /**
     * Sets the value of the pcnmfe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCNMFE(String value) {
        this.pcnmfe = value;
    }

    /**
     * Gets the value of the pcnm1E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCNM1E() {
        return pcnm1E;
    }

    /**
     * Sets the value of the pcnm1E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCNM1E(String value) {
        this.pcnm1E = value;
    }

    /**
     * Gets the value of the pcnm2E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCNM2E() {
        return pcnm2E;
    }

    /**
     * Sets the value of the pcnm2E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCNM2E(String value) {
        this.pcnm2E = value;
    }

    /**
     * Gets the value of the pcnm3E property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCNM3E() {
        return pcnm3E;
    }

    /**
     * Sets the value of the pcnm3E property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCNM3E(String value) {
        this.pcnm3E = value;
    }

}
