//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PE_DATE"/>
 *         &lt;element ref="{}PE_INQR"/>
 *         &lt;element ref="{}PE_TYPE"/>
 *         &lt;element ref="{}PE_MEMB_REF"/>
 *         &lt;element ref="{}PE_PRD"/>
 *         &lt;element ref="{}PE_AMOUNT"/>
 *         &lt;element ref="{}PE_NAME"/>
 *         &lt;element ref="{}PE_RSN" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pedate",
    "peinqr",
    "petype",
    "pemembref",
    "peprd",
    "peamount",
    "pename",
    "persn"
})
@XmlRootElement(name = "PREV_ENQUIRY")
public class PREVENQUIRY {

    @XmlElement(name = "PE_DATE", required = true)
    protected String pedate;
    @XmlElement(name = "PE_INQR", required = true)
    protected String peinqr;
    @XmlElement(name = "PE_TYPE", required = true)
    protected String petype;
    @XmlElement(name = "PE_MEMB_REF", required = true)
    protected String pemembref;
    @XmlElement(name = "PE_PRD", required = true)
    protected String peprd;
    @XmlElement(name = "PE_AMOUNT", required = true)
    protected String peamount;
    @XmlElement(name = "PE_NAME", required = true)
    protected PENAME pename;
    @XmlElement(name = "PE_RSN")
    protected String persn;

    /**
     * Gets the value of the pedate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEDATE() {
        return pedate;
    }

    /**
     * Sets the value of the pedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEDATE(String value) {
        this.pedate = value;
    }

    /**
     * Gets the value of the peinqr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEINQR() {
        return peinqr;
    }

    /**
     * Sets the value of the peinqr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEINQR(String value) {
        this.peinqr = value;
    }

    /**
     * Gets the value of the petype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPETYPE() {
        return petype;
    }

    /**
     * Sets the value of the petype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPETYPE(String value) {
        this.petype = value;
    }

    /**
     * Gets the value of the pemembref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEMEMBREF() {
        return pemembref;
    }

    /**
     * Sets the value of the pemembref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEMEMBREF(String value) {
        this.pemembref = value;
    }

    /**
     * Gets the value of the peprd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEPRD() {
        return peprd;
    }

    /**
     * Sets the value of the peprd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEPRD(String value) {
        this.peprd = value;
    }

    /**
     * Gets the value of the peamount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPEAMOUNT() {
        return peamount;
    }

    /**
     * Sets the value of the peamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPEAMOUNT(String value) {
        this.peamount = value;
    }

    /**
     * Gets the value of the pename property.
     * 
     * @return
     *     possible object is
     *     {@link PENAME }
     *     
     */
    public PENAME getPENAME() {
        return pename;
    }

    /**
     * Sets the value of the pename property.
     * 
     * @param value
     *     allowed object is
     *     {@link PENAME }
     *     
     */
    public void setPENAME(PENAME value) {
        this.pename = value;
    }

    /**
     * Gets the value of the persn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPERSN() {
        return persn;
    }

    /**
     * Sets the value of the persn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPERSN(String value) {
        this.persn = value;
    }

}
