//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PCNAM"/>
 *         &lt;element ref="{}PCDOB"/>
 *         &lt;element ref="{}PCGND"/>
 *         &lt;element ref="{}PCMAR"/>
 *         &lt;element ref="{}PCNAT"/>
 *         &lt;element ref="{}PCEML"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pcnam",
    "pcdob",
    "pcgnd",
    "pcmar",
    "pcnat",
    "pceml"
})
@XmlRootElement(name = "PROVIDED")
public class PROVIDED {

    @XmlElement(name = "PCNAM", required = true)
    protected PCNAM pcnam;
    @XmlElement(name = "PCDOB", required = true)
    protected String pcdob;
    @XmlElement(name = "PCGND", required = true)
    protected String pcgnd;
    @XmlElement(name = "PCMAR", required = true)
    protected String pcmar;
    @XmlElement(name = "PCNAT", required = true)
    protected String pcnat;
    @XmlElement(name = "PCEML", required = true)
    protected String pceml;

    /**
     * Gets the value of the pcnam property.
     * 
     * @return
     *     possible object is
     *     {@link PCNAM }
     *     
     */
    public PCNAM getPCNAM() {
        return pcnam;
    }

    /**
     * Sets the value of the pcnam property.
     * 
     * @param value
     *     allowed object is
     *     {@link PCNAM }
     *     
     */
    public void setPCNAM(PCNAM value) {
        this.pcnam = value;
    }

    /**
     * Gets the value of the pcdob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCDOB() {
        return pcdob;
    }

    /**
     * Sets the value of the pcdob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCDOB(String value) {
        this.pcdob = value;
    }

    /**
     * Gets the value of the pcgnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCGND() {
        return pcgnd;
    }

    /**
     * Sets the value of the pcgnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCGND(String value) {
        this.pcgnd = value;
    }

    /**
     * Gets the value of the pcmar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCMAR() {
        return pcmar;
    }

    /**
     * Sets the value of the pcmar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCMAR(String value) {
        this.pcmar = value;
    }

    /**
     * Gets the value of the pcnat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCNAT() {
        return pcnat;
    }

    /**
     * Sets the value of the pcnat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCNAT(String value) {
        this.pcnat = value;
    }

    /**
     * Gets the value of the pceml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCEML() {
        return pceml;
    }

    /**
     * Sets the value of the pceml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCEML(String value) {
        this.pceml = value;
    }

}
