//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ENQUIRY_TYPE"/>
 *         &lt;element ref="{}REPORT_DATE"/>
 *         &lt;element ref="{}ENQUIRY_NO"/>
 *         &lt;element ref="{}PRODUCT_TYPE"/>
 *         &lt;element ref="{}NO_OF_APPLICANTS"/>
 *         &lt;element ref="{}ACCOUNT_TYPE"/>
 *         &lt;element ref="{}ENQUIRY_REFERENCE"/>
 *         &lt;element ref="{}AMOUNT"/>
 *         &lt;element ref="{}MBR_TYPE"/>
 *         &lt;element ref="{}MBR_STS"/>
 *         &lt;element ref="{}PRCDPT" minOccurs="0"/>
 *         &lt;element ref="{}ENQRSN" minOccurs="0"/>
 *         &lt;element ref="{}FICOG4" minOccurs="0"/>
 *         &lt;element ref="{}CONSUMER" maxOccurs="6"/>
 *         &lt;element ref="{}DISCLAIMER"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "enquirytype",
    "reportdate",
    "enquiryno",
    "producttype",
    "noofapplicants",
    "accounttype",
    "enquiryreference",
    "amount",
    "mbrtype",
    "mbrsts",
    "prcdpt",
    "enqrsn",
    "ficog4",
    "consumer",
    "disclaimer"
})
@XmlRootElement(name = "RSP_REPORT")
public class RSPREPORT {

    @XmlElement(name = "ENQUIRY_TYPE", required = true)
    protected String enquirytype;
    @XmlElement(name = "REPORT_DATE", required = true)
    protected String reportdate;
    @XmlElement(name = "ENQUIRY_NO", required = true)
    protected String enquiryno;
    @XmlElement(name = "PRODUCT_TYPE", required = true)
    protected String producttype;
    @XmlElement(name = "NO_OF_APPLICANTS", required = true)
    protected String noofapplicants;
    @XmlElement(name = "ACCOUNT_TYPE", required = true)
    protected String accounttype;
    @XmlElement(name = "ENQUIRY_REFERENCE", required = true)
    protected String enquiryreference;
    @XmlElement(name = "AMOUNT", required = true)
    protected String amount;
    @XmlElement(name = "MBR_TYPE", required = true)
    protected String mbrtype;
    @XmlElement(name = "MBR_STS", required = true)
    protected String mbrsts;
    @XmlElement(name = "PRCDPT")
    protected String prcdpt;
    @XmlElement(name = "ENQRSN")
    protected String enqrsn;
    @XmlElement(name = "FICOG4")
    protected String ficog4;
    @XmlElement(name = "CONSUMER", required = true)
    protected List<CONSUMER> consumer;
    @XmlElement(name = "DISCLAIMER", required = true)
    protected DISCLAIMER disclaimer;

    /**
     * Gets the value of the enquirytype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENQUIRYTYPE() {
        return enquirytype;
    }

    /**
     * Sets the value of the enquirytype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENQUIRYTYPE(String value) {
        this.enquirytype = value;
    }

    /**
     * Gets the value of the reportdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDATE() {
        return reportdate;
    }

    /**
     * Sets the value of the reportdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDATE(String value) {
        this.reportdate = value;
    }

    /**
     * Gets the value of the enquiryno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENQUIRYNO() {
        return enquiryno;
    }

    /**
     * Sets the value of the enquiryno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENQUIRYNO(String value) {
        this.enquiryno = value;
    }

    /**
     * Gets the value of the producttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODUCTTYPE() {
        return producttype;
    }

    /**
     * Sets the value of the producttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODUCTTYPE(String value) {
        this.producttype = value;
    }

    /**
     * Gets the value of the noofapplicants property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOOFAPPLICANTS() {
        return noofapplicants;
    }

    /**
     * Sets the value of the noofapplicants property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOOFAPPLICANTS(String value) {
        this.noofapplicants = value;
    }

    /**
     * Gets the value of the accounttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCOUNTTYPE() {
        return accounttype;
    }

    /**
     * Sets the value of the accounttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCOUNTTYPE(String value) {
        this.accounttype = value;
    }

    /**
     * Gets the value of the enquiryreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENQUIRYREFERENCE() {
        return enquiryreference;
    }

    /**
     * Sets the value of the enquiryreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENQUIRYREFERENCE(String value) {
        this.enquiryreference = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNT(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the mbrtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRTYPE() {
        return mbrtype;
    }

    /**
     * Sets the value of the mbrtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRTYPE(String value) {
        this.mbrtype = value;
    }

    /**
     * Gets the value of the mbrsts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMBRSTS() {
        return mbrsts;
    }

    /**
     * Sets the value of the mbrsts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMBRSTS(String value) {
        this.mbrsts = value;
    }

    /**
     * Gets the value of the prcdpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRCDPT() {
        return prcdpt;
    }

    /**
     * Sets the value of the prcdpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRCDPT(String value) {
        this.prcdpt = value;
    }

    /**
     * Gets the value of the enqrsn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENQRSN() {
        return enqrsn;
    }

    /**
     * Sets the value of the enqrsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENQRSN(String value) {
        this.enqrsn = value;
    }

    /**
     * Gets the value of the ficog4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFICOG4() {
        return ficog4;
    }

    /**
     * Sets the value of the ficog4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFICOG4(String value) {
        this.ficog4 = value;
    }

    /**
     * Gets the value of the consumer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the consumer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCONSUMER().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONSUMER }
     * 
     * 
     */
    public List<CONSUMER> getCONSUMER() {
        if (consumer == null) {
            consumer = new ArrayList<>();
        }
        return this.consumer;
    }

    /**
     * Gets the value of the disclaimer property.
     * 
     * @return
     *     possible object is
     *     {@link DISCLAIMER }
     *     
     */
    public DISCLAIMER getDISCLAIMER() {
        return disclaimer;
    }

    /**
     * Sets the value of the disclaimer property.
     * 
     * @param value
     *     allowed object is
     *     {@link DISCLAIMER }
     *     
     */
    public void setDISCLAIMER(DISCLAIMER value) {
        this.disclaimer = value;
    }

}
