//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element ref="{}SC_SCORE"/>
 *           &lt;element ref="{}SC_REASON_CODES" minOccurs="0"/>
 *           &lt;element ref="{}SC_SCORECARD"/>
 *           &lt;element ref="{}SC_SCOREINDEX"/>
 *           &lt;element ref="{}SC_MINIMUM"/>
 *           &lt;element ref="{}SC_MAXIMUM"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}SC_ERROR"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "scscore",
    "screasoncodes",
    "scscorecard",
    "scscoreindex",
    "scminimum",
    "scmaximum",
    "scerror"
})
@XmlRootElement(name = "SCORE")
public class SCORE {

    @XmlElement(name = "SC_SCORE")
    protected String scscore;
    @XmlElement(name = "SC_REASON_CODES")
    protected SCREASONCODES screasoncodes;
    @XmlElement(name = "SC_SCORECARD")
    protected String scscorecard;
    @XmlElement(name = "SC_SCOREINDEX")
    protected String scscoreindex;
    @XmlElement(name = "SC_MINIMUM")
    protected String scminimum;
    @XmlElement(name = "SC_MAXIMUM")
    protected String scmaximum;
    @XmlElement(name = "SC_ERROR")
    protected String scerror;

    /**
     * Gets the value of the scscore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCSCORE() {
        return scscore;
    }

    /**
     * Sets the value of the scscore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCSCORE(String value) {
        this.scscore = value;
    }

    /**
     * Gets the value of the screasoncodes property.
     * 
     * @return
     *     possible object is
     *     {@link SCREASONCODES }
     *     
     */
    public SCREASONCODES getSCREASONCODES() {
        return screasoncodes;
    }

    /**
     * Sets the value of the screasoncodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SCREASONCODES }
     *     
     */
    public void setSCREASONCODES(SCREASONCODES value) {
        this.screasoncodes = value;
    }

    /**
     * Gets the value of the scscorecard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCSCORECARD() {
        return scscorecard;
    }

    /**
     * Sets the value of the scscorecard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCSCORECARD(String value) {
        this.scscorecard = value;
    }

    /**
     * Gets the value of the scscoreindex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCSCOREINDEX() {
        return scscoreindex;
    }

    /**
     * Sets the value of the scscoreindex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCSCOREINDEX(String value) {
        this.scscoreindex = value;
    }

    /**
     * Gets the value of the scminimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCMINIMUM() {
        return scminimum;
    }

    /**
     * Sets the value of the scminimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCMINIMUM(String value) {
        this.scminimum = value;
    }

    /**
     * Gets the value of the scmaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCMAXIMUM() {
        return scmaximum;
    }

    /**
     * Sets the value of the scmaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCMAXIMUM(String value) {
        this.scmaximum = value;
    }

    /**
     * Gets the value of the scerror property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCERROR() {
        return scerror;
    }

    /**
     * Sets the value of the scerror property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCERROR(String value) {
        this.scerror = value;
    }

}
