//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:05:30 AM EET 
//


package simahResponse.to.csv.SimahResponseCSV.simah.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CNT_PE"/>
 *         &lt;element ref="{}CNT_MTDE"/>
 *         &lt;element ref="{}CNT_CI" minOccurs="0"/>
 *         &lt;element ref="{}CNT_GCI" minOccurs="0"/>
 *         &lt;element ref="{}CNT_DEF"/>
 *         &lt;element ref="{}EIID" minOccurs="0"/>
 *         &lt;element ref="{}TOT_LIM" minOccurs="0"/>
 *         &lt;element ref="{}TOT_GLIM" minOccurs="0"/>
 *         &lt;element ref="{}TOT_LIAB" minOccurs="0"/>
 *         &lt;element ref="{}TOT_GLIAB" minOccurs="0"/>
 *         &lt;element ref="{}TOT_DEF"/>
 *         &lt;element ref="{}CUR_DB"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cntpe",
    "cntmtde",
    "cntci",
    "cntgci",
    "cntdef",
    "eiid",
    "totlim",
    "totglim",
    "totliab",
    "totgliab",
    "totdef",
    "curdb"
})
@XmlRootElement(name = "SUMMARY")
public class SUMMARY {

    @XmlElement(name = "CNT_PE", required = true)
    protected String cntpe;
    @XmlElement(name = "CNT_MTDE", required = true)
    protected String cntmtde;
    @XmlElement(name = "CNT_CI")
    protected String cntci;
    @XmlElement(name = "CNT_GCI")
    protected String cntgci;
    @XmlElement(name = "CNT_DEF", required = true)
    protected String cntdef;
    @XmlElement(name = "EIID")
    protected String eiid;
    @XmlElement(name = "TOT_LIM")
    protected String totlim;
    @XmlElement(name = "TOT_GLIM")
    protected String totglim;
    @XmlElement(name = "TOT_LIAB")
    protected String totliab;
    @XmlElement(name = "TOT_GLIAB")
    protected String totgliab;
    @XmlElement(name = "TOT_DEF", required = true)
    protected String totdef;
    @XmlElement(name = "CUR_DB", required = true)
    protected String curdb;

    /**
     * Gets the value of the cntpe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTPE() {
        return cntpe;
    }

    /**
     * Sets the value of the cntpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTPE(String value) {
        this.cntpe = value;
    }

    /**
     * Gets the value of the cntmtde property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTMTDE() {
        return cntmtde;
    }

    /**
     * Sets the value of the cntmtde property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTMTDE(String value) {
        this.cntmtde = value;
    }

    /**
     * Gets the value of the cntci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTCI() {
        return cntci;
    }

    /**
     * Sets the value of the cntci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTCI(String value) {
        this.cntci = value;
    }

    /**
     * Gets the value of the cntgci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTGCI() {
        return cntgci;
    }

    /**
     * Sets the value of the cntgci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTGCI(String value) {
        this.cntgci = value;
    }

    /**
     * Gets the value of the cntdef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCNTDEF() {
        return cntdef;
    }

    /**
     * Sets the value of the cntdef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCNTDEF(String value) {
        this.cntdef = value;
    }

    /**
     * Gets the value of the eiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEIID() {
        return eiid;
    }

    /**
     * Sets the value of the eiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEIID(String value) {
        this.eiid = value;
    }

    /**
     * Gets the value of the totlim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTLIM() {
        return totlim;
    }

    /**
     * Sets the value of the totlim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTLIM(String value) {
        this.totlim = value;
    }

    /**
     * Gets the value of the totglim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTGLIM() {
        return totglim;
    }

    /**
     * Sets the value of the totglim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTGLIM(String value) {
        this.totglim = value;
    }

    /**
     * Gets the value of the totliab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTLIAB() {
        return totliab;
    }

    /**
     * Sets the value of the totliab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTLIAB(String value) {
        this.totliab = value;
    }

    /**
     * Gets the value of the totgliab property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTGLIAB() {
        return totgliab;
    }

    /**
     * Sets the value of the totgliab property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTGLIAB(String value) {
        this.totgliab = value;
    }

    /**
     * Gets the value of the totdef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTDEF() {
        return totdef;
    }

    /**
     * Sets the value of the totdef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTDEF(String value) {
        this.totdef = value;
    }

    /**
     * Gets the value of the curdb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCURDB() {
        return curdb;
    }

    /**
     * Sets the value of the curdb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCURDB(String value) {
        this.curdb = value;
    }

}
